const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.LOS,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Behaviors.Physics,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Plugins.sliderbar,
		C3.Behaviors.Pin,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Behaviors.Timer,
		C3.Behaviors.Fade,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Sin,
		C3.Plugins.InstantGamesBridge,
		C3.Plugins.LocalStorage,
		C3.Plugins.Dictionary,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.InstantGamesBridge.Acts.SendMessage,
		C3.Plugins.InstantGamesBridge.Acts.ShowInterstitial,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Physics.Acts.SetAngularDamping,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.Touch.Exps.SpeedForID,
		C3.Behaviors.Physics.Exps.Mass,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Physics.Acts.ApplyTorqueToAngle,
		C3.Plugins.System.Exps.anglediff,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Tilemap.Acts.EraseTileRange,
		C3.Plugins.Tilemap.Exps.TileWidth,
		C3.Plugins.Tilemap.Acts.SetTileRange,
		C3.Plugins.Tilemap.Exps.TileHeight,
		C3.Plugins.Tilemap.Exps.MapDisplayWidth,
		C3.Plugins.Tilemap.Exps.MapDisplayHeight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.scrollto.Cnds.IsEnabled,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Exps.AnimationSpeed,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Physics.Cnds.CompareAngularVelocity,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Tilemap.Cnds.CompareTileAt,
		C3.Plugins.Tilemap.Acts.EraseTile,
		C3.Plugins.Tilemap.Acts.SetTile,
		C3.Plugins.Tilemap.Exps.TileAt,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.Tilemap.Exps.SnapX,
		C3.Plugins.Tilemap.Exps.SnapY,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Behaviors.Pin.Exps.PinnedUID,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Physics.Exps.ContactXAt,
		C3.Behaviors.Physics.Exps.ContactYAt,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Acts.ZMoveToObject,
		C3.Plugins.DrawingCanvas.Acts.SetAngle,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.System.Exps.min,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Plugins.Sprite.Exps.ImagePointCount,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.InstantGamesBridge.Acts.ShowRewarded,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.InstantGamesBridge.Exps.PlatformLanguage,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.InstantGamesBridge.Cnds.OnRewardedRewarded,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.InstantGamesBridge.Cnds.OnInterstitialFailed,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.InstantGamesBridge.Cnds.OnInterstitialOpened,
		C3.Plugins.InstantGamesBridge.Cnds.OnRewardedOpened,
		C3.Plugins.InstantGamesBridge.Cnds.OnInterstitialClosed,
		C3.Plugins.InstantGamesBridge.Cnds.OnRewardedClosed,
		C3.Plugins.InstantGamesBridge.Cnds.OnRewardedFailed,
		C3.Plugins.Touch.Exps.YForID,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Exps.dt,
		C3.Plugins.System.Cnds.EveryTick
	];
};
self.C3_JsPropNameTable = [
	{TouchID: 0},
	{AngleDiffFactor: 0},
	{Name: 0},
	{Life: 0},
	{Life2: 0},
	{ArmorHelmet: 0},
	{ArmorBody: 0},
	{Head: 0},
	{Body: 0},
	{Foot_Left: 0},
	{Foot_Right: 0},
	{WeaponPinnedUID: 0},
	{LineOfSight: 0},
	{Tween: 0},
	{Hand_Left: 0},
	{Hand_Right: 0},
	{Head2: 0},
	{ZHead: 0},
	{ZHand_Left: 0},
	{ZHand_Right: 0},
	{ZBody: 0},
	{ZFoot_Left: 0},
	{ZFoot_Right: 0},
	{Keyboard: 0},
	{DragAndDrop: 0},
	{Physics: 0},
	{Touch: 0},
	{Wall: 0},
	{Ground: 0},
	{CharacterData: 0},
	{Destr: 0},
	{lastVelX: 0},
	{LastVelY: 0},
	{SND: 0},
	{Box: 0},
	{Text: 0},
	{StartX: 0},
	{StartY: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Mouse: 0},
	{SliderBar: 0},
	{TiledBackground: 0},
	{Pin: 0},
	{ButtonAdd: 0},
	{Sprite2: 0},
	{Volume: 0},
	{HeightStart: 0},
	{SliderBack: 0},
	{StartHeight: 0},
	{SliderTop: 0},
	{NameItem: 0},
	{FrameItem: 0},
	{Locked: 0},
	{ButtonItem: 0},
	{CategoryName: 0},
	{ButtonCategory: 0},
	{TouchStartX: 0},
	{DistanceTouchStEnd: 0},
	{TouchEndX: 0},
	{Dis: 0},
	{ShaperCategory: 0},
	{TiledBackground2: 0},
	{Solid: 0},
	{PhysicsGroundTilemap: 0},
	{CheckItem: 0},
	{Type: 0},
	{Ak47: 0},
	{Audio: 0},
	{Damage: 0},
	{Bullet: 0},
	{Sprite3: 0},
	{Particles: 0},
	{Browser: 0},
	{Inst: 0},
	{Timer: 0},
	{Sprite4: 0},
	{Blood: 0},
	{Helmet: 0},
	{Armor: 0},
	{Tank0: 0},
	{Tank1: 0},
	{Tank2: 0},
	{TankWheel: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Shotgun: 0},
	{SniperRiffle: 0},
	{Pistol: 0},
	{MachineGun: 0},
	{GrenadeLauncher: 0},
	{PistolVip: 0},
	{Fade: 0},
	{Sprite8: 0},
	{LayerButton: 0},
	{BackGroundTilemap: 0},
	{Particles2: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{DrawingCanvas: 0},
	{EndY: 0},
	{EndX: 0},
	{HelicopterBase: 0},
	{HellicopterBackPropeller: 0},
	{HelicopterPropeller: 0},
	{Sprite14: 0},
	{DestrNo: 0},
	{BombGrinade: 0},
	{active: 0},
	{Sprite16: 0},
	{Active: 0},
	{BombSmoke: 0},
	{Particles3: 0},
	{BombMine: 0},
	{BombTNT: 0},
	{Explosion1: 0},
	{Explosion2: 0},
	{Sine: 0},
	{FireWork: 0},
	{MiniFireworks: 0},
	{BombFireWork: 0},
	{speed: 0},
	{LR: 0},
	{BombRocket: 0},
	{CopterActive: 0},
	{BombDestr: 0},
	{CopterBase: 0},
	{CopterProreller: 0},
	{BombGrinade2: 0},
	{BombGrinade3: 0},
	{Sprite: 0},
	{Sprite11: 0},
	{BombRocketBack: 0},
	{DrawingCanvas2: 0},
	{BoxDestroy: 0},
	{Particles4: 0},
	{Particles5: 0},
	{Flash: 0},
	{Particles6: 0},
	{Tilemap: 0},
	{ButtonAdd2: 0},
	{ButtonAdd3: 0},
	{InstantGamesBridge: 0},
	{Sprite5: 0},
	{Text2: 0},
	{Sprite12: 0},
	{MapButton: 0},
	{TextName: 0},
	{Text3: 0},
	{SoundButton: 0},
	{BloodButton: 0},
	{Sprite15: 0},
	{LocalStorage: 0},
	{ButtonShop: 0},
	{Sprite13: 0},
	{Particles7: 0},
	{scroll: 0},
	{Sprite17: 0},
	{RewardedSaver: 0},
	{Particles8: 0},
	{Character: 0},
	{Environment: 0},
	{Buttons: 0},
	{Enemy: 0},
	{Weapon: 0},
	{Clothes: 0},
	{Tech: 0},
	{Family1: 0},
	{Bomb: 0},
	{ParticlesF: 0},
	{ButtonSetting: 0},
	{FirstPlay: 0},
	{X: 0},
	{Y: 0},
	{Frame: 0},
	{W: 0},
	{H: 0},
	{Ang1: 0},
	{Ang2: 0},
	{TouchStartY: 0},
	{ScaleRateLayers: 0},
	{SpeedCamera: 0},
	{BuildingFrontOrNo: 0},
	{LayerFront: 0},
	{TimerWold: 0},
	{RadiusExploding: 0},
	{RES: 0},
	{MirrorYesORNo: 0},
	{CharacterName: 0},
	{WeaponUID: 0},
	{AngleHeadChar: 0},
	{AngleFoot_Left: 0},
	{AngleFoot_Right: 0},
	{AngleHand_Left: 0},
	{AngleHand_Right: 0},
	{HelmetMirror: 0},
	{AngleBody: 0},
	{AngleHead: 0},
	{AngleHandLeft: 0},
	{AngleHandRight: 0},
	{AngleFootLeft: 0},
	{AngleFootRight: 0},
	{CameraMove: 0},
	{Block: 0},
	{UID: 0},
	{AddLife: 0},
	{EnemyName: 0},
	{DestroyArmorOrHelmet: 0},
	{Front: 0},
	{IDCharacter: 0},
	{MenuOpen: 0},
	{MenuFrameStatus: 0},
	{sindeY: 0},
	{tindeY: 0},
	{DistT: 0},
	{DistS: 0},
	{TouchStartXDelete: 0},
	{TouchStartYDelete: 0},
	{DeleteFlag: 0},
	{DragAndDropCategory: 0},
	{Category: 0},
	{SoundOn: 0},
	{Ads_timer: 0},
	{Language: 0},
	{MapName: 0},
	{l: 0},
	{FirstLocalLoading: 0},
	{LayerRewarded: 0},
	{FrameRewarded: 0},
	{Layer: 0},
	{ScrollPreActive: 0},
	{ScrollActive: 0},
	{scrollPos: 0},
	{scrollTouchY: 0},
	{scrollMax: 0},
	{scrollSpeed: 0},
	{overEdgeResponce: 0},
	{sensibility: 0}
];

self.InstanceType = {
	Head: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	Foot_Left: class extends self.ISpriteInstance {},
	Foot_Right: class extends self.ISpriteInstance {},
	Hand_Left: class extends self.ISpriteInstance {},
	Hand_Right: class extends self.ISpriteInstance {},
	Head2: class extends self.ISpriteInstance {},
	ZHead: class extends self.ISpriteInstance {},
	ZHand_Left: class extends self.ISpriteInstance {},
	ZHand_Right: class extends self.ISpriteInstance {},
	ZBody: class extends self.ISpriteInstance {},
	ZFoot_Left: class extends self.ISpriteInstance {},
	ZFoot_Right: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	DragAndDrop: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	CharacterData: class extends self.IArrayInstance {},
	Box: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Camera: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	ButtonAdd: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	SliderBack: class extends self.ISpriteInstance {},
	SliderTop: class extends self.ISpriteInstance {},
	ButtonItem: class extends self.ISpriteInstance {},
	ButtonCategory: class extends self.ISpriteInstance {},
	ShaperCategory: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	PhysicsGroundTilemap: class extends self.ITilemapInstance {},
	CheckItem: class extends self.ITiledBackgroundInstance {},
	Ak47: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Browser: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Blood: class extends self.IParticlesInstance {},
	Helmet: class extends self.ISpriteInstance {},
	Armor: class extends self.ISpriteInstance {},
	Tank0: class extends self.ISpriteInstance {},
	Tank1: class extends self.ISpriteInstance {},
	Tank2: class extends self.ISpriteInstance {},
	TankWheel: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Shotgun: class extends self.ISpriteInstance {},
	SniperRiffle: class extends self.ISpriteInstance {},
	Pistol: class extends self.ISpriteInstance {},
	MachineGun: class extends self.ISpriteInstance {},
	GrenadeLauncher: class extends self.ISpriteInstance {},
	PistolVip: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	LayerButton: class extends self.ISpriteInstance {},
	BackGroundTilemap: class extends self.ITilemapInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	HelicopterBase: class extends self.ISpriteInstance {},
	HellicopterBackPropeller: class extends self.ISpriteInstance {},
	HelicopterPropeller: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	BombGrinade: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	BombSmoke: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	BombMine: class extends self.ISpriteInstance {},
	BombTNT: class extends self.ISpriteInstance {},
	Explosion1: class extends self.ISpriteInstance {},
	Explosion2: class extends self.ISpriteInstance {},
	FireWork: class extends self.ISpriteInstance {},
	MiniFireworks: class extends self.ISpriteInstance {},
	BombFireWork: class extends self.ISpriteInstance {},
	BombRocket: class extends self.ISpriteInstance {},
	CopterBase: class extends self.ISpriteInstance {},
	CopterProreller: class extends self.ISpriteInstance {},
	BombGrinade2: class extends self.ISpriteInstance {},
	BombGrinade3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	BombRocketBack: class extends self.ISpriteInstance {},
	DrawingCanvas2: class extends self.IDrawingCanvasInstance {},
	BoxDestroy: class extends self.ISpriteInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Flash: class extends self.ISpriteInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	ButtonAdd2: class extends self.ISpriteInstance {},
	ButtonAdd3: class extends self.ISpriteInstance {},
	InstantGamesBridge: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	MapButton: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	BloodButton: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	ButtonShop: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Particles7: class extends self.IParticlesInstance {},
	scroll: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	RewardedSaver: class extends self.IDictionaryInstance {},
	Particles8: class extends self.IParticlesInstance {},
	Character: class extends self.ISpriteInstance {},
	Environment: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Weapon: class extends self.ISpriteInstance {},
	Clothes: class extends self.ISpriteInstance {},
	Tech: class extends self.ISpriteInstance {},
	Family1: class extends self.IDrawingCanvasInstance {},
	Bomb: class extends self.ISpriteInstance {},
	ParticlesF: class extends self.IParticlesInstance {},
	ButtonSetting: class extends self.ISpriteInstance {}
}