/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function a(a){a=String(a);return a.charAt(0).toUpperCase()+a.slice(1)}function d(a,b){var e=-1,f=a?a.length:0;if("number"==typeof f&&-1<f&&f<=y)for(;++e<f;)b(a[e],e,a);else c(a,b)}function b(b){b=String(b).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(b)?b:a(b)}function c(a,b){for(var e in a)x.call(a,e)&&b(a[e],e,a)}function g(b){return null==b?a(b):z.call(b).slice(8,-1)}function h(a,b){var e=null!=a?typeof a[b]:"number";return!/^(?:boolean|number|string|undefined)$/.test(e)&&
("object"==e?!!a[b]:!0)}function e(a){return String(a).replace(/([ -])(?!$)/g,"$1?")}function l(a,b){var e=null;d(a,function(f,c){e=b(e,f,c,a)});return e}function f(a){function d(f){return l(f,function(f,c){var d=c.pattern||e(c);!f&&(f=RegExp("\\b"+d+" *\\d+[.\\w_]*","i").exec(a)||RegExp("\\b"+d+" *\\w+-[\\w]*","i").exec(a)||RegExp("\\b"+d+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(a))&&((f=String(c.label&&!RegExp(d,"i").test(c.label)?c.label:f).split("/"))[1]&&!/[\d.]+/.test(f[0])&&(f[0]+=
" "+f[1]),c=c.label||c,f=b(f[0].replace(RegExp(d,"i"),c).replace(RegExp("; *(?:"+c+"[_-])?","i")," ").replace(RegExp("("+c+")[-_.]?(\\w)","i"),"$1 $2")));return f})}function p(b){return l(b,function(b,e){return b||(RegExp(e+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(a)||0)[1]||null})}var n=m,r=a&&"object"==typeof a&&"String"!=g(a);r&&(n=a,a=null);var q=n.navigator||{},t=q.userAgent||"";a||(a=t);var K=r?!!q.likeChrome:/\bChrome\b/.test(a)&&!/internal|\n/i.test(z.toString()),
S=r?"Object":"ScriptBridgingProxyObject",y=r?"Object":"Environment",x=r&&n.java?"JavaPackage":g(n.java),A=r?"Object":"RuntimeObject";y=(x=/\bJava/.test(x)&&n.java)&&g(n.environment)==y;var T=x?"a":"\u03b1",U=x?"b":"\u03b2",P=n.document||{},G=n.operamini||n.opera,L=w.test(L=r&&G?G["[[Class]]"]:g(G))?L:G=null,k,M=a;r=[];var N=null,H=a==t;t=H&&G&&"function"==typeof G.version&&G.version();var B=function(b){return l(b,function(b,f){return b||RegExp("\\b"+(f.pattern||e(f))+"\\b","i").exec(a)&&(f.label||
f)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),u=function(b){return l(b,function(b,f){return b||RegExp("\\b"+(f.pattern||e(f))+"\\b","i").exec(a)&&(f.label||f)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),C=d([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),E=function(b){return l(b,function(b,f,c){return b||(f[C]||f[/^[a-z]+(?: +[a-z]+\b)*/i.exec(C)]||RegExp("\\b"+e(c)+"(?:\\b|\\w*\\d)","i").exec(a))&&c})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),v=function(f){return l(f,function(f,c){var d=c.pattern||e(c);if(!f&&(f=RegExp("\\b"+d+"(?:/[\\d.]+|[ \\w.]*)","i").exec(a))){var l=f,t=c.label||c,h={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};d&&t&&/^Win/i.test(l)&&!/^Windows Phone /i.test(l)&&(h=h[/[\d.]+$/.exec(l)])&&(l="Windows "+h);l=String(l);d&&t&&(l=l.replace(RegExp(d,"i"),t));f=l=b(l.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return f})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);B&&(B=[B]);E&&!C&&(C=d([E]));if(k=/\bGoogle TV\b/.exec(C))C=k[0];/\bSimulator\b/i.test(a)&&(C=(C?C+" ":"")+"Simulator");"Opera Mini"==u&&/\bOPiOS\b/.test(a)&&r.push("running in Turbo/Uncompressed mode");"IE"==u&&/\blike iPhone OS\b/.test(a)?(k=f(a.replace(/like iPhone OS/,"")),E=k.manufacturer,C=k.product):/^iP/.test(C)?(u||(u="Safari"),v="iOS"+((k=/ OS ([\d_]+)/i.exec(a))?" "+k[1].replace(/_/g,"."):"")):"Konqueror"!=u||/buntu/i.test(v)?E&&"Google"!=E&&(/Chrome/.test(u)&&
!/\bMobile Safari\b/i.test(a)||/\bVita\b/.test(C))||/\bAndroid\b/.test(v)&&/^Chrome/.test(u)&&/\bVersion\//i.test(a)?(u="Android Browser",v=/\bAndroid\b/.test(v)?v:"Android"):"Silk"==u?(/\bMobi/i.test(a)||(v="Android",r.unshift("desktop mode")),/Accelerated *= *true/i.test(a)&&r.unshift("accelerated")):"PaleMoon"==u&&(k=/\bFirefox\/([\d.]+)\b/.exec(a))?r.push("identifying as Firefox "+k[1]):"Firefox"==u&&(k=/\b(Mobile|Tablet|TV)\b/i.exec(a))?(v||(v="Firefox OS"),C||(C=k[1])):!u||(k=!/\bMinefield\b/i.test(a)&&
/\b(?:Firefox|Safari)\b/.exec(u))?(u&&!C&&/[\/,]|^[^(]+?\)/.test(a.slice(a.indexOf(k+"/")+8))&&(u=null),(k=C||E||v)&&(C||E||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(v))&&(u=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(v)?v:k)+" Browser")):"Electron"==u&&(k=(/\bChrome\/([\d.]+)\b/.exec(a)||0)[1])&&r.push("Chromium "+k):v="Kubuntu";t||(t=p(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",e(u),"(?:Firefox|Minefield|NetFront)"]));
if(k="iCab"==B&&3<parseFloat(t)&&"WebKit"||/\bOpera\b/.test(u)&&(/\bOPR\b/.test(a)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(a)&&!/^(?:Trident|EdgeHTML)$/.test(B)&&"WebKit"||!B&&/\bMSIE\b/i.test(a)&&("Mac OS"==v?"Tasman":"Trident")||"WebKit"==B&&/\bPlayStation\b(?! Vita\b)/i.test(u)&&"NetFront")B=[k];"IE"==u&&(k=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(a)||0)[1])?(u+=" Mobile",v="Windows Phone "+(/\+$/.test(k)?k:k+".x"),r.unshift("desktop mode")):/\bWPDesktop\b/i.test(a)?(u="IE Mobile",v="Windows Phone 8.x",
r.unshift("desktop mode"),t||(t=(/\brv:([\d.]+)/.exec(a)||0)[1])):"IE"!=u&&"Trident"==B&&(k=/\brv:([\d.]+)/.exec(a))&&(u&&r.push("identifying as "+u+(t?" "+t:"")),u="IE",t=k[1]);if(H){if(h(n,"global"))if(x&&(k=x.lang.System,M=k.getProperty("os.arch"),v=v||k.getProperty("os.name")+" "+k.getProperty("os.version")),y){try{t=n.require("ringo/engine").version.join("."),u="RingoJS"}catch(R){(k=n.system)&&k.global.system==n.system&&(u="Narwhal",v||(v=k[0].os||null))}u||(u="Rhino")}else"object"==typeof n.process&&
!n.process.browser&&(k=n.process)&&("object"==typeof k.versions&&("string"==typeof k.versions.electron?(r.push("Node "+k.versions.node),u="Electron",t=k.versions.electron):"string"==typeof k.versions.nw&&(r.push("Chromium "+t,"Node "+k.versions.node),u="NW.js",t=k.versions.nw)),u||(u="Node.js",M=k.arch,v=k.platform,t=(t=/[\d.]+/.exec(k.version))?t[0]:null));else g(k=n.runtime)==S?(u="Adobe AIR",v=k.flash.system.Capabilities.os):g(k=n.phantom)==A?(u="PhantomJS",t=(k=k.version||null)&&k.major+"."+k.minor+
"."+k.patch):"number"==typeof P.documentMode&&(k=/\bTrident\/(\d+)/i.exec(a))?(t=[t,P.documentMode],(k=+k[1]+4)!=t[1]&&(r.push("IE "+t[1]+" mode"),B&&(B[1]=""),t[1]=k),t="IE"==u?String(t[1].toFixed(1)):t[0]):"number"==typeof P.documentMode&&/^(?:Chrome|Firefox)\b/.test(u)&&(r.push("masking as "+u+" "+t),u="IE",t="11.0",B=["Trident"],v="Windows");v=v&&b(v)}t&&(k=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(t)||/(?:alpha|beta)(?: ?\d)?/i.exec(a+";"+(H&&q.appMinorVersion))||/\bMinefield\b/i.test(a)&&
"a")&&(N=/b/i.test(k)?"beta":"alpha",t=t.replace(RegExp(k+"\\+?$"),"")+("beta"==N?U:T)+(/\d+\+?/.exec(k)||""));if("Fennec"==u||"Firefox"==u&&/\b(?:Android|Firefox OS)\b/.test(v))u="Firefox Mobile";else if("Maxthon"==u&&t)t=t.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(C))"Xbox 360"==C&&(v=null),"Xbox 360"==C&&/\bIEMobile\b/.test(a)&&r.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(u)&&(!u||C||/Browser|Mobi/.test(u))||"Windows CE"!=v&&!/Mobi/i.test(a))if("IE"==u&&H)try{null===n.external&&
r.unshift("platform preview")}catch(R){r.unshift("embedded")}else(/\bBlackBerry\b/.test(C)||/\bBB10\b/.test(a))&&(k=(RegExp(C.replace(/ +/g," *")+"/([.\\d]+)","i").exec(a)||0)[1]||t)?(k=[k,/BB10/.test(a)],v=(k[1]?(C=null,E="BlackBerry"):"Device Software")+" "+k[0],t=null):this!=c&&"Wii"!=C&&(H&&G||/Opera/.test(u)&&/\b(?:MSIE|Firefox)\b/i.test(a)||"Firefox"==u&&/\bOS X (?:\d+\.){2,}/.test(v)||"IE"==u&&(v&&!/^Win/.test(v)&&5.5<t||/\bWindows XP\b/.test(v)&&8<t||8==t&&!/\bTrident\b/.test(a)))&&!w.test(k=
f.call(c,a.replace(w,"")+";"))&&k.name&&(k="ing as "+k.name+((k=k.version)?" "+k:""),w.test(u)?(/\bIE\b/.test(k)&&"Mac OS"==v&&(v=null),k="identify"+k):(k="mask"+k,u=L?b(L.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(k)&&(v=null),H||(t=null)),B=["Presto"],r.push(k));else u+=" Mobile";if(k=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(a)||0)[1]){k=[parseFloat(k.replace(/\.(\d)$/,".0$1")),k];if("Safari"==u&&"+"==k[1].slice(-1))u="WebKit Nightly",N="alpha",t=k[1].slice(0,-1);else if(t==k[1]||t==(k[2]=
(/\bSafari\/([\d.]+\+?)/i.exec(a)||0)[1]))t=null;k[1]=(/\bChrome\/([\d.]+)/i.exec(a)||0)[1];537.36==k[0]&&537.36==k[2]&&28<=parseFloat(k[1])&&"WebKit"==B&&(B=["Blink"]);H&&(K||k[1])?(B&&(B[1]="like Chrome"),k=k[1]||(k=k[0],530>k?1:532>k?2:532.05>k?3:533>k?4:534.03>k?5:534.07>k?6:534.1>k?7:534.13>k?8:534.16>k?9:534.24>k?10:534.3>k?11:535.01>k?12:535.02>k?"13+":535.07>k?15:535.11>k?16:535.19>k?17:536.05>k?18:536.1>k?19:537.01>k?20:537.11>k?"21+":537.13>k?23:537.18>k?24:537.24>k?25:537.36>k?26:"Blink"!=
B?"27":"28")):(B&&(B[1]="like Safari"),k=(k=k[0],400>k?1:500>k?2:526>k?3:533>k?4:534>k?"4+":535>k?5:537>k?6:538>k?7:601>k?8:"8"));B&&(B[1]+=" "+(k+="number"==typeof k?".x":/[.+]/.test(k)?"":"+"));"Safari"==u&&(!t||45<parseInt(t))&&(t=k)}"Opera"==u&&(k=/\bzbov|zvav$/.exec(v))?(u+=" ",r.unshift("desktop mode"),"zvav"==k?(u+="Mini",t=null):u+="Mobile",v=v.replace(RegExp(" *"+k+"$"),"")):"Safari"==u&&/\bChrome\b/.exec(B&&B[1])&&(r.unshift("desktop mode"),u="Chrome Mobile",t=null,/\bOS X\b/.test(v)?(E=
"Apple",v="iOS 4.3+"):v=null);t&&0==t.indexOf(k=/[\d.]+$/.exec(v))&&-1<a.indexOf("/"+k+"-")&&(v=String(v.replace(k,"")).replace(/^ +| +$/g,""));B&&!/\b(?:Avant|Nook)\b/.test(u)&&(/Browser|Lunascape|Maxthon/.test(u)||"Safari"!=u&&/^iOS/.test(v)&&/\bSafari\b/.test(B[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(u)&&B[1])&&(k=B[B.length-1])&&r.push(k);r.length&&(r=["("+r.join("; ")+")"]);E&&C&&0>C.indexOf(E)&&r.push("on "+E);C&&r.push((/^on /.test(r[r.length-
1])?"":"on ")+C);if(v){var Q=(k=/ ([\d.+]+)$/.exec(v))&&"/"==v.charAt(v.length-k[0].length-1);v={architecture:32,family:k&&!Q?v.replace(k[0],""):v,version:k?k[1]:null,toString:function(){var a=this.version;return this.family+(a&&!Q?" "+a:"")+(64==this.architecture?" 64-bit":"")}}}(k=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(M))&&!/\bi686\b/i.test(M)?(v&&(v.architecture=64,v.family=v.family.replace(RegExp(" *"+k),"")),u&&(/\bWOW64\b/i.test(a)||H&&/\w(?:86|32)$/.test(q.cpuClass||q.platform)&&!/\bWin64; x64\b/i.test(a))&&
r.unshift("32-bit")):v&&/^OS X/.test(v.family)&&"Chrome"==u&&39<=parseFloat(t)&&(v.architecture=64);a||(a=null);n={};n.description=a;n.layout=B&&B[0];n.manufacturer=E;n.name=u;n.prerelease=N;n.product=C;n.ua=a;n.version=u&&t;n.os=v||{architecture:null,family:null,version:null,toString:function(){return"null"}};n.parse=f;n.toString=function(){return this.description||""};n.version&&r.unshift(t);n.name&&r.unshift(u);v&&u&&(v!=String(v).split(" ")[0]||v!=u.split(" ")[0]&&!C)&&r.push(C?"("+v+")":"on "+
v);r.length&&(n.description=r.join(" "));return n}var p={"function":!0,object:!0},m=p[typeof window]&&window||this,n=p[typeof exports]&&exports;p=p[typeof module]&&module&&!module.nodeType&&module;var q=n&&p&&"object"==typeof global&&global;!q||q.global!==q&&q.window!==q&&q.self!==q||(m=q);var y=Math.pow(2,53)-1,w=/\bOpera/;q=Object.prototype;var x=q.hasOwnProperty,z=q.toString,A=f();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(m.platform=A,define(function(){return A})):n&&
p?c(A,function(a,b){n[b]=a}):m.platform=A}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],d=0;d<a.length;d++){var b=document.createElement("meta");b.name=a[d].name;b.content=a[d].content;var c=window.document.head.querySelector('meta[name="'+b.name+'"]');c&&c.parentNode.removeChild(c);window.document.head.appendChild(b)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;
case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}$(document).ready(function(){platform&&"iPhone"===platform.product&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&!iosInIframe()&&iosResize()});
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},d="undefined"!==typeof module&&module.exports,b="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,c=function(){for(var b,c=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],f=0,d=c.length,h={};f<d;f++)if((b=c[f])&&b[1]in a){for(f=0;f<b.length;f++)h[c[0][f]]=b[f];return h}return!1}(),g={change:c.fullscreenchange,error:c.fullscreenerror},h={request:function(e){var d=c.requestFullscreen;e=e||a.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))e[d]();
else e[d](b&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){a[c.exitFullscreen]()},toggle:function(a){this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},on:function(b,c){var f=g[b];f&&a.addEventListener(f,c,!1)},off:function(b,c){var f=g[b];f&&a.removeEventListener(f,c,!1)},raw:c};c?(Object.defineProperties(h,{isFullscreen:{get:function(){return!!a[c.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[c.fullscreenElement]}},
enabled:{enumerable:!0,get:function(){return!!a[c.fullscreenEnabled]}}}),d?module.exports=h:window.screenfull=h):d?module.exports=!1:window.screenfull=!1})();var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var d=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var g=b.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var h=b.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+d+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";g.appendChild(h);c.insertBefore(g,b.head);
a=7==h["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(g)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}
function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width");_checkOrientation(d,a);var b=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),c=CANVAS_WIDTH*b;b*=CANVAS_HEIGHT;if(b<a){var g=a-b;b+=g;c+=CANVAS_WIDTH/CANVAS_HEIGHT*g}else c<d&&(g=d-c,c+=g,b+=CANVAS_HEIGHT/CANVAS_WIDTH*g);g=a/2-b/2;var h=d/2-c/2,e=CANVAS_WIDTH/c;if(h*e<-EDGEBOARD_X||g*e<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,g=(a-b)/2,h=(d-c)/2,e=CANVAS_WIDTH/c;s_iOffsetX=-1*h*e;s_iOffsetY=-1*g*e;0<=g&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos();null!==s_oMenu&&s_oMenu.refreshButtonPos();null!==s_oSelectPlayers&&s_oSelectPlayers.refreshButtonPos();s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*c,s_oStage.canvas.height=2*b,canvas.style.width=c+"px",canvas.style.height=
b+"px",s_oStage.scaleX=s_oStage.scaleY=2*Math.min(c/CANVAS_WIDTH,b/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",c+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=b,s_iScaleFactor=Math.min(c/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>g?$("#canvas").css("top",g+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",h+"px");fullscreenHandler()}}
function _checkOrientation(a,d){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>d?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function playSound(a,d,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(d),s_aSounds[a].loop(b),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(d)}function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(d)}
function createBitmap(a,d,b){var c=new createjs.Bitmap(a),g=new createjs.Shape;d&&b?g.graphics.beginFill("#fff").drawRect(0,0,d,b):g.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=g;return c}function createSprite(a,d,b,c,g,h){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-c,g,h);a.hitArea=d;return a}function pad(a,d,b){a+="";return a.length>=d?a:Array(d-a.length+1).join(b||"0")+a}
function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}function rotateVector2D(a,d){var b=d.getX()*Math.cos(a)+d.getY()*Math.sin(a),c=d.getX()*-Math.sin(a)+d.getY()*Math.cos(a);d.set(b,c)}function tweenVectorsOnX(a,d,b){return a+b*(d-a)}function shuffle(a){for(var d=a.length,b,c;0!==d;)c=Math.floor(Math.random()*d),--d,b=a[d],a[d]=a[c],a[c]=b;return a}
function bubbleSort(a){do{var d=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(d=a[b],a[b]=a[b+1],a[b+1]=d,d=!0)}while(d)}function compare(a,d){return a.index>d.index?-1:a.index<d.index?1:0}function easeLinear(a,d,b,c){return b*a/c+d}function easeInQuad(a,d,b,c){return b*(a/=c)*a+d}function easeInSine(a,d,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+d}function easeInCubic(a,d,b,c){return b*(a/=c)*a*a+d}
function getTrajectoryPoint(a,d){var b=new createjs.Point,c=(1-a)*(1-a),g=a*a;b.x=c*d.start.x+2*(1-a)*a*d.traj.x+g*d.end.x;b.y=c*d.start.y+2*(1-a)*a*d.traj.y+g*d.end.y;return b}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var b="";b=10>d?b+("0"+d+":"):b+(d+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,d){var b=getBounds(a,.9);var c=getBounds(d,.98);return calculateIntersection(b,c)}
function calculateIntersection(a,d){var b,c,g,h;var e=a.x+(b=a.width/2);var l=a.y+(c=a.height/2);var f=d.x+(g=d.width/2);var p=d.y+(h=d.height/2);e=Math.abs(e-f)-(b+g);l=Math.abs(l-p)-(c+h);return 0>e&&0>l?(e=Math.min(Math.min(a.width,d.width),-e),l=Math.min(Math.min(a.height,d.height),-l),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:e,height:l,rect1:a,rect2:d}):null}
function getBounds(a,d){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,g=c.length,h;for(h=0;h<g;h++){var e=getBounds(c[h],1);e.x<b.x&&(b.x=e.x);e.y<b.y&&(b.y=e.y);e.x+e.width>b.x2&&(b.x2=e.x+e.width);e.y+e.height>b.y2&&(b.y2=e.y+e.height)}Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{if(a instanceof createjs.Bitmap){g=
a.sourceRect||a.image;h=g.width*d;var l=g.height*d}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){g=a.spriteSheet.getFrame(a.currentFrame);h=g.rect.width;l=g.rect.height;c=g.regX;var f=g.regY}else b.x=a.x||0,b.y=a.y||0;else b.x=a.x||0,b.y=a.y||0;c=c||0;h=h||0;f=f||0;l=l||0;b.regX=c;b.regY=f;g=a.localToGlobal(0-c,0-f);e=a.localToGlobal(h-c,l-f);h=a.localToGlobal(h-c,0-f);c=a.localToGlobal(0-c,l-f);b.x=
Math.min(Math.min(Math.min(g.x,e.x),h.x),c.x);b.y=Math.min(Math.min(Math.min(g.y,e.y),h.y),c.y);b.width=Math.max(Math.max(Math.max(g.x,e.x),h.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(g.y,e.y),h.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,b,c;0<d;)c=Math.floor(Math.random()*d),d--,b=a[d],a[d]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;if(a.type in b)document.body.className=b[a.type];else if(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className){if(s_oMain.stopUpdate(),!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.muted=!0}else s_oMain.startUpdate(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(createjs.Sound.muted=
!1)}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function ctlArcadeResume(){null!==s_oMain&&(s_oMain.startUpdate(),!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&(createjs.Sound.muted=!0)}function ctlArcadePause(){null!==s_oMain&&(s_oMain.stopUpdate(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(createjs.Sound.muted=!1))}function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),b=0;b<d.length;b++){var c=d[b].split("=");if(c[0]==a)return c[1]}}
function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.enabled&&(s_bFullscreen=screen.height<window.innerHeight+3&&screen.height>window.innerHeight-3?!0:!1,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut(),null!==s_oSelectPlayers&&s_oSelectPlayers.resetFullscreenBut())}
if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut();null!==s_oSelectPlayers&&s_oSelectPlayers.resetFullscreenBut()});
function CSpriteLibrary(){var a,d,b,c,g,h;this.init=function(e,l,f){b=d=0;c=e;g=l;h=f;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){g.call(h)};this._onSpriteLoaded=function(){c.call(h);++b==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1920,CANVAS_HEIGHT=1080,EDGEBOARD_X=256,EDGEBOARD_Y=84,PRIMARY_FONT="comfortaabold",FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,ENABLE_FULLSCREEN=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_SELECT_PLAYERS=4,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_CARD_DEALED=6,ENABLE_CHECK_ORIENTATION,AD_SHOW_COUNTER,NUM_PLAYERS,STARTING_NUM_CARDS,CARD_WIDTH=156,CARD_HEIGHT=242,aHandPos=[];
aHandPos.num_player_2=[{x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2+350},{x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-350}];aHandPos.num_player_3=[{x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2+350},{x:CANVAS_WIDTH/2-650,y:CANVAS_HEIGHT/2-40},{x:CANVAS_WIDTH/2+650,y:CANVAS_HEIGHT/2}];aHandPos.num_player_4=[{x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2+350},{x:CANVAS_WIDTH/2-650,y:CANVAS_HEIGHT/2-40},{x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-350},{x:CANVAS_WIDTH/2+650,y:CANVAS_HEIGHT/2-40}];TEXT_GAMEOVER="CONGRATULATION! YOU WON!";
TEXT_LOSE="SORRY, THE PLAYER ";TEXT_LOSE2=" WON THIS GAME";TEXT_SCORE="YOUR SCORE";TEXT_RESTART="RESTART";TEXT_MOVES="MOVES";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_SELECT_PLAYERS="SELECT THE NUMBER OF PLAYERS !";TEXT_SELECT_COLOR="SELECT A COLOR ";TEXT_TUTORIAL1="WELCOME TO FOUR COLORS! MATCH CARDS BY COLOR OR NUMBER AND BE THE FIRST TO GET RID OF THEM!";TEXT_TUTORIAL2="ACTION CARDS WILL MIX THE GAME UP!\n\nDRAW TWO FORCES THE NEXT PLAYER TO PICK TWO CARDS AND FORFEIT THE TURN";TEXT_TUTORIAL3="SKIP CARD STOPS THE NEXT PLAYER";
TEXT_TUTORIAL4="REVERSE CARD SWITCHES THE GAME WISE";TEXT_TUTORIAL5="THE WILD CARD CAN BE PLACED ON ANY CARD AT ANY TIME AND ALLOWS YOU TO CHANGE THE COLOR TO PLAY ";TEXT_TUTORIAL6="THE WILD DRAW FOUR IS A SPECIAL WILD THAT ALLOWS YOU TO CHANGE THE COLOR AND FORCES THE NEXT PLAYER TO PICK 4 CARDS. TO USE THIS CARD YOU MUST HAVE NO OTHER ALTERNATIVE CARDS TO PLAY";TEXT_TUTORIAL7="DO NOT FORGET TO PRESS THE 1 BUTTON WHEN YOU'LL HAVE ONLY ONE CARD LEFT OR YOU'LL PICK 2 PENALTY CARDS!";
TEXT_PLAYER_1="PLAYER 1";TEXT_PLAYER_2="PLAYER 2";TEXT_PLAYER_3="PLAYER 3";TEXT_PLAYER_4="PLAYER 4";TEXT_ALERT_1="YOU MUST PRESS ' 1 ' BUTTON WHEN YOU HAVE JUST ONE CARD. TWO CARDS PENALITY";var TEXT_PRELOADER_CONTINUE="START";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,d,b,c,g,h,e,l,f,p;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();p=new createjs.Container;s_oStage.addChild(p)};this.unload=function(){p.removeAllChildren();f.unload()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.addChild(m);m=s_oSpriteLibrary.getSprite("200x200");e=createBitmap(m);e.regX=.5*m.width;e.regY=.5*m.height;e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-180;p.addChild(e);l=new createjs.Shape;l.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(e.x-100,e.y-100,200,200,10);p.addChild(l);e.mask=l;
m=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(m);c.x=CANVAS_WIDTH/2-m.width/2;c.y=CANVAS_HEIGHT/2+50;p.addChild(c);a=m.width;d=m.height;g=new createjs.Shape;g.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(c.x,c.y,1,d);p.addChild(g);c.mask=g;b=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2+100;b.textBaseline="alphabetic";b.textAlign="center";p.addChild(b);m=s_oSpriteLibrary.getSprite("but_start");f=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/
2,m,TEXT_PRELOADER_CONTINUE,"Arial","#000","bold 50",p);f.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);f.setVisible(!1);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.addChild(h);createjs.Tween.get(h).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(h);p.removeChild(h)})};this._onButStartRelease=function(){s_oMain.onRemovePreloader()};this.refreshLoader=function(e){b.text=e+"%";100===e&&(f.setVisible(!0),b.visible=!1,c.visible=
!1);g.graphics.clear();e=Math.floor(e*a/100);g.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(c.x,c.y,e,d)};this._init()}
function CMain(a){var d,b=0,c=0,g=STATE_LOADING,h,e;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!0;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(FPS),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=FPS;navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();d=!0};this.soundLoaded=function(){b++;h.refreshLoader(Math.floor(b/c*100))};this._initSounds=function(){var a=[];a.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});a.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});a.push({path:"./sounds/",filename:"game_over",
loop:!1,volume:1,ingamename:"game_over"});a.push({path:"./sounds/",filename:"card_dealing",loop:!1,volume:1,ingamename:"card_dealing"});a.push({path:"./sounds/",filename:"snap",loop:!1,volume:1,ingamename:"snap"});a.push({path:"./sounds/",filename:"card",loop:!1,volume:1,ingamename:"card"});a.push({path:"./sounds/",filename:"special_card",loop:!1,volume:1,ingamename:"special_card"});a.push({path:"./sounds/",filename:"change_color",loop:!1,volume:1,ingamename:"change_color"});c+=a.length;s_aSounds=
[];for(var b=0;b<a.length;b++)s_aSounds[a[b].ingamename]=new Howl({src:[a[b].path+a[b].filename+".mp3",a[b].path+a[b].filename+".ogg"],autoplay:!1,preload:!0,loop:a[b].loop,volume:a[b].volume,onload:s_oMain.soundLoaded()})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("credits_panel","./sprites/credits_panel.png");
s_oSpriteLibrary.addSprite("select_color_panel","./sprites/select_color_panel.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_yes_big","./sprites/but_yes_big.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_exit_big.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_uno",
"./sprites/but_uno.png");s_oSpriteLibrary.addSprite("but_p2","./sprites/but_p2.png");s_oSpriteLibrary.addSprite("but_p3","./sprites/but_p3.png");s_oSpriteLibrary.addSprite("but_p4","./sprites/but_p4.png");s_oSpriteLibrary.addSprite("but_red","./sprites/_oButRed.png");s_oSpriteLibrary.addSprite("but_green","./sprites/_oButGreen.png");s_oSpriteLibrary.addSprite("but_blue","./sprites/_oButBlue.png");s_oSpriteLibrary.addSprite("but_yellow","./sprites/_oButYellow.png");s_oSpriteLibrary.addSprite("stop_turn",
"./sprites/stop_turn.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_select_players","./sprites/bg_select_players.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_arrow","./sprites/arrow.png");
s_oSpriteLibrary.addSprite("but_skip","./sprites/but_skip.png");s_oSpriteLibrary.addSprite("line_player","./sprites/line_players.png");s_oSpriteLibrary.addSprite("cards","./sprites/cards.png");s_oSpriteLibrary.addSprite("colors","./sprites/colors.png");s_oSpriteLibrary.addSprite("draw_four_anim","./sprites/draw_4.png");s_oSpriteLibrary.addSprite("draw_two_anim","./sprites/draw_2.png");s_oSpriteLibrary.addSprite("stop_turn_anim","./sprites/stop_turn.png");s_oSpriteLibrary.addSprite("clock_wise_anim",
"./sprites/change_clockwise.png");s_oSpriteLibrary.addSprite("change_color","./sprites/change_color.png");s_oSpriteLibrary.addSprite("cloud_uno","./sprites/cloud.png");s_oSpriteLibrary.addSprite("finger","./sprites/finger.png");s_oSpriteLibrary.addSprite("shuffle_anim","./sprites/shuffle_anim.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;h.refreshLoader(Math.floor(b/c*100))};this._onAllImagesLoaded=function(){};this.onRemovePreloader=
function(){h.unload();s_oSoundtrack=playSound("soundtrack",1,!0);this.gotoMenu()};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoSelectPlayers=function(){new CSelectPlayers;g=STATE_SELECT_PLAYERS};this.gotoGame=function(a){s_bFirstGame=!1===a?!1:!0;e=new CGame(l);g=STATE_GAME};this.gotoHelp=function(){new CHelp;g=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=
function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&e.update();s_oStage.update(a)}};s_oMain=this;var l=a;ENABLE_CHECK_ORIENTATION=a.check_orientation;
ENABLE_FULLSCREEN=a.fullscreen;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bFullscreen=!1,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack=null,s_oCanvas,s_bFirstGame=!1,s_aSounds;
function CTextButton(a,d,b,c,g,h,e,l){var f,p,m,n,q,y,w,x,z,A,r,D;this._init=function(a,b,c,d,e,l,h,g){f=!1;n=[];q=[];D=createBitmap(c);p=c.width;m=c.height;var t=Math.ceil(h/20);A=new createjs.Text(d,h+"px "+e,"#000000");var K=A.getBounds();A.textAlign="center";A.lineWidth=.9*p;A.textBaseline="alphabetic";A.x=c.width/2+t;A.y=Math.floor(c.height/2)+K.height/3+t;r=new createjs.Text(d,h+"px "+e,l);r.textAlign="center";r.textBaseline="alphabetic";r.lineWidth=.9*p;r.x=c.width/2;r.y=Math.floor(c.height/
2)+K.height/3;z=new createjs.Container;z.x=a;z.y=b;z.regX=c.width/2;z.regY=c.height/2;s_bMobile||(z.cursor="pointer");z.addChild(D,A,r);!1!==g&&s_oStage.addChild(z);this._initListener()};this.unload=function(){z.off("mousedown",w);z.off("pressup",x);s_oStage.removeChild(z)};this.setVisible=function(a){z.visible=a};this.setAlign=function(a){r.textAlign=a;A.textAlign=a};this.enable=function(){f=!1;D.filters=[];D.cache(0,0,p,m)};this.disable=function(){f=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);
D.filters=[new createjs.ColorMatrixFilter(a)];D.cache(0,0,p,m)};this._initListener=function(){w=z.on("mousedown",this.buttonDown);x=z.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){n[a]=b;q[a]=c};this.addEventListenerWithParams=function(a,b,c,f){n[a]=b;q[a]=c;y=f};this.buttonRelease=function(){f||(playSound("click",1,!1),z.scaleX=1,z.scaleY=1,n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(q[ON_MOUSE_UP],y))};this.buttonDown=function(){f||(z.scaleX=.9,z.scaleY=.9,n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN]))};
this.setPosition=function(a,b){z.x=a;z.y=b};this.changeText=function(a){r.text=a;A.text=a};this.setX=function(a){z.x=a};this.setY=function(a){z.y=a};this.getButtonImage=function(){return z};this.getX=function(){return z.x};this.getY=function(){return z.y};this.getSprite=function(){return z};this._init(a,d,b,c,g,h,e,l);return this}
function CToggle(a,d,b,c,g){var h,e,l,f,p,m;this._init=function(a,b,c,f,d){e=[];l=[];var g=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});h=f;m=createSprite(g,"state_"+h,c.width/2/2,c.height/2,c.width/2,c.height);m.x=a;m.y=b;m.stop();m.cursor="pointer";d.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",f);m.off("pressup",p);g.removeChild(m)};this._initListener=function(){f=
m.on("mousedown",this.buttonDown);p=m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){e[a]=b;l[a]=c};this.setActive=function(a){h=a;m.gotoAndStop("state_"+h)};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;playSound("click",1,!1);h=!h;m.gotoAndStop("state_"+h);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(l[ON_MOUSE_UP],h)};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setPosition=function(a,b){m.x=a;m.y=b};this._init(a,
d,b,c,g)}
function CGfxButton(a,d,b,c){var g,h,e,l,f,p,m;this._init=function(a,b,c,f){g=!1;h=1;e=[];l=[];m=createBitmap(c);m.x=a;m.y=b;m.scaleX=m.scaleY=h;m.regX=c.width/2;m.regY=c.height/2;m.cursor="pointer";f.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",f);m.off("pressup",p);c.removeChild(m)};this.setVisible=function(a){m.visible=a};this.setClickable=function(a){g=!a};this._initListener=function(){f=m.on("mousedown",this.buttonDown);p=m.on("pressup",this.buttonRelease)};this.addEventListener=
function(a,b,c){e[a]=b;l[a]=c};this.buttonRelease=function(){g||(m.scaleX=h,m.scaleY=h,e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(l[ON_MOUSE_UP]))};this.buttonDown=function(){g||(m.scaleX=.9*h,m.scaleY=.9*h,playSound("click",1,!1),e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN]))};this.pulseAnimation=function(){createjs.Tween.get(m).to({scaleX:.9*h,scaleY:.9*h},850,createjs.Ease.quadOut).to({scaleX:h,scaleY:h},650,createjs.Ease.quadIn).call(function(){n.pulseAnimation()})};this.trembleAnimation=
function(){createjs.Tween.get(m).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){n.trebleAnimation()})};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};var n=this;this._init(a,d,b,c);return this}
function CPanelTutorial(){var a,d,b,c,g,h,e;this.init=function(){s_oInterface.setButtonUno(!1);e=new createjs.Container;h=0;a=new createjs.Container;a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;d=new createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d.regX=398;d.regY=258.5;d.alpha=.8;a.addChild(d);s_oStage.addChild(a);b=new CGfxButton(a.getBounds().width/2-50,0,s_oSpriteLibrary.getSprite("but_arrow"),a);b.addEventListener(ON_MOUSE_DOWN,this.onButNext,this);var l=s_oSpriteLibrary.getSprite("but_arrow");
c=new CGfxButton(-(a.getBounds().width/2-50),0,l,a);c.addEventListener(ON_MOUSE_DOWN,this.onButBack,this);c.getButtonImage().rotation=180;g=new CGfxButton(a.getBounds().width/2-53,a.getBounds().height/2-53,s_oSpriteLibrary.getSprite("but_skip"),a);g.addEventListener(ON_MOUSE_DOWN,this.onButSkip,this);this.loadPage(h)};this.loadPage=function(d){switch(d){case 0:c.setVisible(!1);d=new createjs.Text(TEXT_TUTORIAL1," 30px "+PRIMARY_FONT,"#FFFFFF");d.lineWidth=320;d.x=-60;d.y=-95;d.align="center";var f=
new CCard(-215,0,e,"card_1_7",0,0);e.addChild(d);f.setAnimTutorial("tutorial");a.addChild(e);break;case 1:c.setVisible(!0);d=new createjs.Text(TEXT_TUTORIAL2," 30px "+PRIMARY_FONT,"#FFFFFF");d.lineWidth=320;d.x=-60;d.y=-130;d.align="center";f=new CCard(-215,0,e,"card_0_12",0,0);e.addChild(d);f.setAnimTutorial("draw2tutorial");break;case 2:d=new createjs.Text(TEXT_TUTORIAL3," 30px "+PRIMARY_FONT,"#FFFFFF");d.lineWidth=320;d.x=-60;d.y=-45;d.align="center";f=new CCard(-215,0,e,"card_1_7",0,0);e.addChild(d);
f.setAnimTutorial("stopTurnTutorial");break;case 3:d=new createjs.Text(TEXT_TUTORIAL4," 30px "+PRIMARY_FONT,"#FFFFFF");d.lineWidth=320;d.x=-60;d.y=-55;d.align="center";f=new CCard(-215,0,e,"card_1_7",0,0);e.addChild(d);f.setAnimTutorial("changeClockWiseTutorial");break;case 4:d=new createjs.Text(TEXT_TUTORIAL5," 30px "+PRIMARY_FONT,"#FFFFFF");d.lineWidth=320;d.x=-60;d.y=-95;d.align="center";f=new CCard(-215,0,e,"color",0,0);e.addChild(d);f.instantShow();break;case 5:b.setVisible(!0);d=new createjs.Text(TEXT_TUTORIAL6,
" 30px "+PRIMARY_FONT,"#FFFFFF");d.lineWidth=320;d.x=-60;d.y=-170;d.align="center";f=new CCard(-215,0,e,"draw_four",0,0);e.addChild(d);f.instantShow();break;case 6:b.setVisible(!1),d=new createjs.Text(TEXT_TUTORIAL7," 30px "+PRIMARY_FONT,"#FFFFFF"),d.lineWidth=320,d.x=-60,d.y=-100,d.align="center",f=new createBitmap(s_oSpriteLibrary.getSprite("but_uno")),f.regX=50,f.regY=50.5,f.x=-215,f.scaleX=1.5,f.scaleY=1.5,e.addChild(d),e.addChild(f)}};this.onButNext=function(){h++;e.removeAllChildren();this.loadPage(h)};
this.onButBack=function(){h--;e.removeAllChildren();this.loadPage(h)};this.onButSkip=function(){s_oStage.removeChild(a);s_oInterface.setButtonUno(!0);s_oGame.startGame()};this.init()}
function CTurnManager(){var a,d=0,b=0;this.init=function(){a=!0;b=0;d=3===b?0:b+1;s_oTurnManager=this};this.changeClockWise=function(){a=!0===a?!1:!0};this.nextTurn=function(){!0===a?b===NUM_PLAYERS-1?(b=0,d=1):(b++,d=b===NUM_PLAYERS-1?0:b+1):0===b?(b=NUM_PLAYERS-1,d=NUM_PLAYERS-2):(b--,d=0===b?NUM_PLAYERS-1:b-1)};this.checkTurn=function(){return b};this.prevTurn=function(){!0===a?0===b?(b=NUM_PLAYERS-1,d=NUM_PLAYERS-2):(b--,d=0===b?NUM_PLAYERS-1:b-1):b===NUM_PLAYERS-1?(b=0,d=1):(b++,d=b===NUM_PLAYERS-
1?0:b+1)};this.checkPrevTurn=function(){return!0===a?0===b?NUM_PLAYERS-1:b-1:b===NUM_PLAYERS-1?0:b+1};this.checkNextPlayer=function(){return d};this.setTurn=function(c){b=c;d=!0===a?b===NUM_PLAYERS-1?0:b+1:0===b?NUM_PLAYERS-1:b-1};this.getClockWise=function(){return a};this.init()}s_oTurnManager=null;
function CListernableObject(){var a;this._init=function(){a=[]};this.addEventListener=function(d,b,c){a[d]={cb:b,owner:c}};this.removeEventListener=function(d){a[d]=null};this.callEvent=function(d,b){a[d]&&(b?a[d].cb.apply(a[d].owner,[b]):a[d].cb.call(a[d].owner))};this._init()}
function CAnimation(){var a,d,b,c,g,h,e,l;this.init=function(){e=!1;var f=s_oSpriteLibrary.getSprite("draw_four_anim");f={images:[f],frames:{width:292,height:290,regX:146,regY:145},animations:{anim:{frames:[0,1,2,3,4,5,6,7,8,9,10,11,12,13],next:"stop",speed:.8},reverse:{frames:[13,12,11,10,9,8,7,6,5,4,3,2,1,0],next:[0],speed:.8},stop:[13]}};f=new createjs.SpriteSheet(f);a=new createjs.Sprite(f,0);f=s_oSpriteLibrary.getSprite("draw_two_anim");f={images:[f],frames:{width:292,height:322,regX:146,regY:161},
animations:{anim:{frames:[0,1,2,3,4,5,6,7,8,9,10,11,12,13],next:"stop",speed:.8},reverse:{frames:[13,12,11,10,9,8,7,6,5,4,3,2,1,0],next:[0],speed:.8},stop:[13]}};f=new createjs.SpriteSheet(f);d=new createjs.Sprite(f,0);f=s_oSpriteLibrary.getSprite("stop_turn_anim");b=new createBitmap(f,292,300);f=s_oSpriteLibrary.getSprite("clock_wise_anim");c=new createBitmap(f,292,300);f=s_oSpriteLibrary.getSprite("change_color");f={images:[f],frames:{width:328,height:315,regX:164,regY:157.5},animations:{anim:{frames:[0,
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],next:"anim",speed:.8},stop:[16],color_0:{frames:[0,1,2,3,4,5,6],speed:.8},color_1:{frames:[0,1,2],speed:.8},color_2:{frames:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],speed:.8},color_3:{frames:[0,1,2,3,4,5,6,7,8,9,10],speed:.8}}};f=new createjs.SpriteSheet(f);g=new createjs.Sprite(f,0);f=s_oSpriteLibrary.getSprite("shuffle_anim");f={images:[f],frames:{width:403,height:386,regX:201.5,regY:193},animations:{anim:{frames:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],
next:"anim"},idle:[17]}};f=new createjs.SpriteSheet(f);l=new createjs.Sprite(f,"idle")};this.drawFourAnim=function(){a.alpha=0;a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.scaleX=.01;a.scaleY=.01;s_oStage.addChild(a);a.stop();playSound("special_card",.5,!1);(new createjs.Tween.get(a)).to({alpha:1,scaleX:1.4,scaleY:1.4},200,createjs.Ease.cubicOut).wait(200).call(function(){a.gotoAndPlay("anim")}).wait(1E3).call(function(){a.gotoAndPlay("reverse")}).wait(200).to({alpha:0,scaleX:.01,scaleY:.01},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(a);
s_oGame.onEndDrawFour()})};this.drawTwoAnim=function(){d.alpha=0;d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2;d.scaleX=.01;d.scaleY=.01;s_oStage.addChild(d);d.stop();playSound("special_card",.5,!1);(new createjs.Tween.get(d)).to({alpha:1,scaleX:1.4,scaleY:1.4},200,createjs.Ease.cubicOut).wait(200).call(function(){d.gotoAndPlay("anim");setVolume("special_card",.2)}).wait(1E3).call(function(){d.gotoAndPlay("reverse");setVolume("special_card",.1)}).wait(200).to({alpha:0,scaleX:.01,scaleY:.01},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(d);
s_oGame.onEndDrawTwo()})};this.stopTurn=function(){b.alpha=0;b.regX=146;b.regY=150;b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;b.scaleX=.01;b.scaleY=.01;s_oStage.addChild(b);playSound("game_over",1,!1);(new createjs.Tween.get(b)).to({alpha:1,scaleX:2,scaleY:2},200,createjs.Ease.cubicOut).to({scaleX:1.6,scaleY:1.6},200).to({scaleX:2,scaleY:2},200).to({scaleX:1.6,scaleY:1.6},200).to({scaleX:2,scaleY:2},200).to({alpha:0,scaleX:.01,scaleY:.01},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(b);
s_oGame.onNextTurn()})};this.changeClockWise=function(a){c.alpha=0;c.rotation=0;c.regX=146;c.regY=150;c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;c.scaleX=.01;c.scaleY=.01;s_oStage.addChild(c);playSound("special_card",.5,!1);!1===a?(new createjs.Tween.get(c)).to({alpha:1,scaleX:2,scaleY:2},200,createjs.Ease.cubicOut).to({rotation:360},500).wait(500).to({rotation:-360},500).wait(500).to({alpha:0,scaleX:.01,scaleY:.01},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(c);s_oGame.onNextTurn()}):
(new createjs.Tween.get(c)).to({alpha:1,scaleX:2,scaleY:2},200,createjs.Ease.cubicOut).to({rotation:-360},500).wait(500).to({rotation:360},500).wait(500).to({alpha:0,scaleX:.01,scaleY:.01},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(c);s_oGame.onNextTurn()})};this.changeColor=function(a){h=a;g.alpha=0;g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2;g.scaleX=.01;g.scaleY=.01;s_oStage.addChild(g);g.stop();playSound("change_color",.5,!1);(new createjs.Tween.get(g)).to({alpha:1,scaleX:1.4,
scaleY:1.4},200,createjs.Ease.cubicOut).call(function(){g.gotoAndPlay("anim")}).wait(1300).call(function(){g.gotoAndStop(16);g.gotoAndPlay("color_"+a);e=!0;g.on("animationend",s_oCAnimation.endAnimation)})};this.endAnimation=function(){!0===e&&(stopSound("change_color"),playSound("special_card",1,!1),e=!1,g.off("animationend",s_oCAnimation.endAnimation),g.stop(),(new createjs.Tween.get(g)).to({scaleX:2,scaleY:2},250).to({scaleX:1.4,scaleY:1.4},250).to({scaleX:2,scaleY:2},250).to({scaleX:1.4,scaleY:1.4},
250).to({alpha:0,scaleX:.1,scaleY:.1},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(g);g.gotoAndStop(0);s_oInterface.refreshColor(h);s_oGame.onNextTurn()}))};this.shuffleAnimation=function(a,b,c,d){l.alpha=0;l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT/2;l.scaleX=.01;l.scaleY=.01;s_oStage.addChild(l);l.stop();(new createjs.Tween.get(l)).to({alpha:1,scaleX:1.6,scaleY:1.6},400,createjs.Ease.cubicOut).call(function(){l.gotoAndPlay("anim");playSound("card_dealing",1,!0)}).wait(1700).call(function(){l.gotoAndStop("idle");
stopSound("change_color")}).to({alpha:0,scaleX:.01,scaleY:.01},300,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(l);s_oGame.onEndShuffle(a,b,c,d)})};this.init();s_oCAnimation=this}s_oCAnimation=null;
function CMenu(){var a,d,b,c,g,h,e,l,f,p,m,n,q=null,y=null;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(e);var w=s_oSpriteLibrary.getSprite("but_play");l=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-200,w,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);w=s_oSpriteLibrary.getSprite("but_info");g=w.width/2+10;h=w.height/2+10;m=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-240,w,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onCreditsBut,
this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)w=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-w.height/2-10,c=w.height/2+10,p=new CToggle(b,c,w,s_bAudioActive,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);w=window.document;var x=w.documentElement;q=x.requestFullscreen||x.mozRequestFullScreen||x.webkitRequestFullScreen||x.msRequestFullscreen;y=w.exitFullscreen||w.mozCancelFullScreen||w.webkitExitFullscreen||w.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(q=!1);q&&screenfull.enabled&&
(w=s_oSpriteLibrary.getSprite("but_fullscreen"),a=g+w.width/2+10,d=h,n=new CToggle(a,d,w,s_bFullscreen,s_oStage),n.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(f);createjs.Tween.get(f).to({alpha:0},1E3).call(function(){f.visible=!1});null!==s_oSoundtrack&&setVolume("soundtrack",1);this.refreshButtonPos()};this.unload=function(){l.unload();l=null;f.visible=!1;m.unload();if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)p.unload(),p=null;q&&screenfull.enabled&&n.unload();s_oStage.removeAllChildren();s_oMenu=null};this.refreshButtonPos=function(){m.setPosition(g+s_iOffsetX,s_iOffsetY+h);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(b-s_iOffsetX,s_iOffsetY+c);q&&screenfull.enabled&&n.setPosition(a+s_iOffsetX,d+s_iOffsetY)};this.resetFullscreenBut=function(){q&&screenfull.enabled&&n.setActive(s_bFullscreen)};this._onFullscreen=function(){s_bFullscreen?y.call(window.document):q.call(window.document.documentElement);
sizeHandler()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCreditsBut=function(){new CCreditsPanel};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoSelectPlayers()};s_oMenu=this;this._init()}var s_oMenu=null;
function CSelectPlayers(){var a,d,b,c,g,h,e,l,f=null,p=null,m;this._init=function(){var n=createBitmap(s_oSpriteLibrary.getSprite("bg_select_players"));s_oStage.addChild(n);n=s_oSpriteLibrary.getSprite("but_p2");g=new CGfxButton(CANVAS_WIDTH/2-450,CANVAS_HEIGHT-500,n,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onButP2,this);n=s_oSpriteLibrary.getSprite("but_p3");h=new CGfxButton(CANVAS_WIDTH/2+10,CANVAS_HEIGHT-500,n,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onButP3,this);n=s_oSpriteLibrary.getSprite("but_p4");
e=new CGfxButton(CANVAS_WIDTH/2+450,CANVAS_HEIGHT-500,n,s_oStage);e.addEventListener(ON_MOUSE_UP,this._onButP4,this);n=new createjs.Text(TEXT_SELECT_PLAYERS," 55px "+PRIMARY_FONT,"#FFF");n.textAlign="center";n.x=CANVAS_WIDTH/2;n.y=300;n.textBaseline="alphabetic";s_oStage.addChild(n);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-n.height/2-10,c=n.height/2+10,m=new CToggle(b,c,n,s_bAudioActive,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);n=window.document;var q=n.documentElement;f=q.requestFullscreen||q.mozRequestFullScreen||q.webkitRequestFullScreen||q.msRequestFullscreen;p=n.exitFullscreen||n.mozCancelFullScreen||n.webkitExitFullscreen||n.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(f=!1);f&&screenfull.enabled&&(n=s_oSpriteLibrary.getSprite("but_fullscreen"),a=n.width/4+10,d=n.height/2+10,l=new CToggle(a,d,n,s_bFullscreen,s_oStage),l.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));this.refreshButtonPos()};this._onButP2=
function(){NUM_PLAYERS=2;this.unload();$(s_oMain).trigger("select_players",2);s_oMain.gotoGame()};this._onButP3=function(){NUM_PLAYERS=3;this.unload();$(s_oMain).trigger("select_players",3);s_oMain.gotoGame()};this._onButP4=function(){NUM_PLAYERS=4;this.unload();$(s_oMain).trigger("select_players",4);s_oMain.gotoGame()};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;f&&screenfull.enabled&&l.unload();g.unload();h.unload();e.unload();s_oStage.removeAllChildren();
s_oSelectPlayers=null};this.refreshButtonPos=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(b-s_iOffsetX,s_iOffsetY+c);f&&screenfull.enabled&&l.setPosition(a+s_iOffsetX,d+s_iOffsetY)};this.resetFullscreenBut=function(){f&&screenfull.enabled&&l.setActive(s_bFullscreen)};this._onFullscreen=function(){s_bFullscreen?p.call(window.document):f.call(window.document.documentElement);sizeHandler()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};
s_oSelectPlayers=this;this._init()}var s_oSelectPlayers=null;
function CCard(a,d,b,c,g,h){var e=!1,l,f,p,m,n,q,y,w,x,z;this._init=function(a,b,c,d,e,h,t){z=c;p=d;m=e;n=h;l=!1;f=0===n||2===n?"red":"black";x=new createjs.Container;x.x=a;x.y=b;z.addChild(x);a={images:[s_oSpriteLibrary.getSprite("cards")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_0_0:[0],card_0_1:[1],card_0_2:[2],card_0_3:[3],card_0_4:[4],card_0_5:[5],card_0_6:[6],card_0_7:[7],card_0_8:[8],card_0_9:[9],card_0_10:[10],card_0_11:[11],card_0_12:[12],
card_1_0:[13],card_1_1:[14],card_1_2:[15],card_1_3:[16],card_1_4:[17],card_1_5:[18],card_1_6:[19],card_1_7:[20],card_1_8:[21],card_1_9:[22],card_1_10:[23],card_1_11:[24],card_1_12:[25],card_2_0:[26],card_2_1:[27],card_2_2:[28],card_2_3:[29],card_2_4:[30],card_2_5:[31],card_2_6:[32],card_2_7:[33],card_2_8:[34],card_2_9:[35],card_2_10:[36],card_2_11:[37],card_2_12:[38],card_3_0:[39],card_3_1:[40],card_3_2:[41],card_3_3:[42],card_3_4:[43],card_3_5:[44],card_3_6:[45],card_3_7:[46],card_3_8:[47],card_3_9:[48],
card_3_10:[49],card_3_11:[50],card_3_12:[51],color:[52],draw_four:[53],back:[54],tutorial:{frames:[20,5,47,31],speed:.1},draw2tutorial:{frames:[12,25,38,51],speed:.1},stopTurnTutorial:{frames:[10,23,36,49],speed:.1},changeClockWiseTutorial:{frames:[11,24,37,50],speed:.1}}};a=new createjs.SpriteSheet(a);w=createSprite(a,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);w.stop();x.addChild(w);w.on("mousedown",this._mouseDown);q=[];y=[]};this.getCardSprite=function(){return w};this.setAnimTutorial=
function(a){w.gotoAndPlay(a)};this.unload=function(){w.off("mousedown",this._mouseDown);z.removeChild(x)};this.unloadEvent=function(){w.off("mousedown",this._mouseDown)};this.saveInfo=function(){return{szFotogram:p,iRank:m,iSuit:n,bValue:!0}};this.changeInfo=function(a,b,c){p=a;m=b;n=c};this.instantShow=function(){w.gotoAndStop(p)};this.setValue=function(a){w.gotoAndStop(p);playSound("card",1,!1);createjs.Tween.get(x).to({scaleX:1},200).call(function(){})};this.setActive=function(a){a?x.addChild(void 0):
x.removeChild(void 0)};this.setVisible=function(a){x.visible=!0===a?!0:!1};this.onSetTurned=function(){l=!0};this.offSetTurned=function(){l=!1};this.moveCard=function(a,b,c,d){var f=this;createjs.Tween.get(x).wait(d).to({x:a,y:b},c,createjs.Ease.linear).call(function(){s_oGame.playedCard(f)})};this.moveCardFirstHand=function(a,b,c,d){var f=this;createjs.Tween.get(x).wait(d).to({x:a,y:b},c,createjs.Ease.cubicOut).call(function(){playSound("card_dealing",1,!1);s_oGame.onCardDealed(f)})};this.moveFirstLastCard=
function(a,b,c,d){var f=this;createjs.Tween.get(x).wait(d).to({x:a,y:b},c,createjs.Ease.linear).call(function(){s_oGame.onFirstLastCardDealed(f)})};this.setOnTop=function(){z.addChildAt(x,z.numChildren)};this.moveToSuit=function(a,b,c){createjs.Tween.get(x).wait(c).to({x:a,y:b},200,createjs.Ease.cubicOut).call(function(){s_oGame.stackInSuit(A)})};this.setPlaced=function(){e=!0;A.showCard()};this.stackInPlace=function(a,b,c){createjs.Tween.get(x).to({x:a,y:b},c,createjs.Ease.cubicOut).call(function(){l=
!0})};this.stackAndDeactive=function(a,b,c){createjs.Tween.get(x).to({x:a,y:b},c,createjs.Ease.cubicOut)};this._mouseDown=function(a){!1!==l&&s_oGame.pickCard(A,a)};this.getPlaced=function(){return e};this.showCard=function(a,b){var c=this;createjs.Tween.get(x).wait(a).to({scaleX:.1},200).call(function(){c.setValue(b)}).call(function(){l=!0})};this.showCardNoInput=function(a,b){var c=this;createjs.Tween.get(x).wait(a).to({scaleX:.1},200).call(function(){c.setValue(b)}).call(function(){l=!1})};this.hideCard=
function(){var a=this;createjs.Tween.get(x).to({scaleX:.1},200).call(function(){a.setBack()})};this.setPos=function(a,b){x.x=a;x.y=b};this.setBack=function(){l=!1;w.gotoAndStop("back");var a=this;createjs.Tween.get(x).to({scaleX:1},200).call(function(){a.cardHidden()})};this.cardHidden=function(){q[ON_CARD_HIDE]&&q[ON_CARD_HIDE].call(y[ON_CARD_HIDE],this)};this.getRank=function(){return m};this.getSuit=function(){return n};this.getColor=function(){return f};this.getFotogram=function(){return p};this.getPos=
function(){return{x:x.x,y:x.y}};this.getSprite=function(){return x};this.getLogicRect=function(){return new createjs.Rectangle(x.x-CARD_WIDTH/2,x.y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT)};this.getTurned=function(){return l};var A=this;this._init(a,d,b,c,g,h);this.getGlobalToLocal=function(a,b){return w.globalToLocal(a/s_oStage.scaleX,b/s_oStage.scaleY)}}
function CDeckDisplayer(a,d,b){var c,g,h,e;this._init=function(){c=[];g=new createjs.Container;h=!1;g.x=a;g.y=d;e=b;e.addChild(g,e);g.on("mousedown",this.onDraw,this)};this.initializeDeck=function(){for(var a,b=0;4>b;b++)for(var d=0;10>d;d++)a=d,c.push(new CCard(0,0,g,"card_"+b+"_"+d,a,b));for(b=0;4>b;b++)for(d=0;9>d;d++)a=d+1,c.push(new CCard(0,0,g,"card_"+b+"_"+a,a,b));for(b=0;4>b;b++)for(d=0;2>d;d++)c.push(new CCard(0,0,g,"card_"+b+"_10",10,b)),c.push(new CCard(0,0,g,"card_"+b+"_11",11,b)),c.push(new CCard(0,
0,g,"card_"+b+"_12",12,b));for(b=0;4>b;b++)c.push(new CCard(0,0,g,"color",13,4)),c.push(new CCard(0,0,g,"draw_four",14,4))};this.shuffle=function(){var a;for(a=c.length;a;a--){var b=Math.floor(Math.random()*a);var d=c[a-1];c[a-1]=c[b];c[b]=d}};this.moveContainer=function(a,b,c,d){createjs.Tween.get(g).wait(d).to({x:a,y:b},c,createjs.Ease.linear)};this.takeFirstLastCard=function(){for(;4===c[c.length-1].getSuit();)this.shuffle();return c.pop()};this.takeLastCard=function(){return c.pop()};this.getLastCard=
function(){return c[c.length-1]};this.getCardByIndex=function(a){return c[a]};this.removeCardByIndex=function(a){return c.splice(a,1)};this.pushCard=function(a){c.push(a)};this.getContainer=function(){return g};this.getLength=function(){return c.length};this.onDraw=function(){if(!1===h)s_oGame.onDraw()};this.disableInputUsedCards=function(){c[c.length-1].offSetTurned()};this.disableInputDraw=function(){h=!0};this.enableInputDraw=function(){h=!1};this.getIndexChild=function(){return s_oStage.getChildIndex(g)};
this.setChildDepth=function(a){s_oStage.addChildAt(g,a)};this.getGlobalPosition=function(){return{x:g.x,y:g.y}};this.setOnTop=function(){e.addChildAt(g,e.numChildren)};this.addNewCardUnderTheDeck=function(a){for(var b=0;b<a.length;b++)c.push(a[b])};this.removeAllCardUnderTheDeck=function(){for(var a=[],b=0;b<c.length-1;b++)a.push(c.shift());return a};this._init()}
function CHandDisplayer(a,d,b,c,g,h,e){var l,f,p,m,n,q,y,w,x=!1;this.init=function(){l=a;f=d;p=[];m=new createjs.Container;m.x=b;m.y=c;w=h;w.addChild(m);var g=s_oSpriteLibrary.getSprite("line_player");g={images:[g],frames:{width:524,height:18,regX:262,regY:9},animations:{off:[0],on:[1],idle:{frames:[0,1],speed:.1}}};g=new createjs.SpriteSheet(g);n=new createjs.Sprite(g,"off");n.stop();q=new createjs.Text(e," 34px "+PRIMARY_FONT,"#FFFFFF");0!==l?(n.x=CANVAS_WIDTH/2,c>CANVAS_HEIGHT/2?(q.x=CANVAS_WIDTH/
2+40,n.y=c-135,q.y=c-178):(q.x=CANVAS_WIDTH/2-195,n.y=c+135,q.y=c+140)):(n.y=CANVAS_HEIGHT/2,b<CANVAS_WIDTH/2?(n.x=b+100,n.rotation=90,q.x=b+150,q.y=c+70,q.rotation=90):(n.x=b-100,n.rotation=-90,q.x=b-150,q.y=c+6,q.rotation=-90));s_oStage.addChild(n);s_oStage.addChild(q);g=s_oSpriteLibrary.getSprite("cloud_uno");g={images:[g],frames:{width:261,height:194,regX:130.5,regY:97},animations:{cloud1:[0],cloud2:[1]}};g=new createjs.SpriteSheet(g);y=new createjs.Sprite(g,"cloud1");y.alpha=0;y.scaleX=.1;y.scaleY=
.1};this.getGlobalPosition=function(){for(var a=0,b=0,c=0;c<p.length;c++)0!==l?a+=CARD_WIDTH/2:b+=CARD_HEIGHT/2;return{x:m.x+a,y:m.y+b}};this.getContainerPos=function(){return{x:m.x,y:m.y}};this.getCardPositionByIndex=function(a){a=p[a].getPos();return{x:a.x,y:a.y}};this.searchIndexCard=function(a){for(var b=0;b<p.length;b++)if(a===p[b])return b};this.removeCardByIndex=function(a){return p.splice(a,1)};this.getPosNewCard=function(){return{x:p.length*l,y:p.length*f}};this.pushCard=function(a){p.push(a);
if(0===f&&c>CANVAS_HEIGHT/2)p[p.length-1].getCardSprite().on("mouseover",this.onMouseOver)};this.getContainer=function(){return m};this.getLastCard=function(){return p[p.length-1]};this.getLength=function(){return p.length};this.centerContainer=function(){var a=m.getBounds();0!==l?createjs.Tween.get(m).to({x:CANVAS_WIDTH/2-a.width/2+CARD_WIDTH/2},300,createjs.Ease.linear):createjs.Tween.get(m).to({y:CANVAS_HEIGHT/2-a.height/2+CARD_HEIGHT/1.5-40},300,createjs.Ease.linear)};this.setOnTop=function(){w.addChildAt(m,
w.numChildren)};this.setChildDepth=function(a){a>m.s_oStage.numChild-1&&(a=m.s_oStage.numChild-1);s_oStage.addChildAt(a)};this.getContainerInfo=function(){return m.getBounds()};this.getCardByIndex=function(a){return p[a]};this.organizeHand=function(a){var b=this;if(0!==l)for(var c=0;c<p.length;c++)a=l*c,createjs.Tween.get(p[c].getSprite()).to({x:a},300,createjs.Ease.linear).call(b.centerContainer);else for(c=0;c<p.length;c++)a=f*c,createjs.Tween.get(p[c].getSprite()).to({y:a},300,createjs.Ease.linear).call(function(){b.centerContainer()})};
this.setOnTurn=function(){q.alpha=1;x=!0;if(!1===createjs.Tween.hasActiveTweens(q)&&0===g)this.onTweenPlayer();n.gotoAndStop("on")};this.onTweenPlayer=function(){var a=this;!0===x?(new createjs.Tween.get(q)).to({alpha:.15},500).to({alpha:1},500).call(function(){a.onTweenPlayer()}):q.alpha=.15};this.setOffTurn=function(){createjs.Tween.removeTweens(q);x=!1;q.alpha=.15;n.gotoAndStop("off")};this.checkUno=function(){1===p.length&&(this.setOnTop(),0!==l?c<CANVAS_HEIGHT/2?(y.gotoAndStop("cloud2"),y.x=
CANVAS_WIDTH/2-270,y.y=CANVAS_HEIGHT/2-300):(y.gotoAndStop("cloud1"),y.x=CANVAS_WIDTH/2+300,y.y=CANVAS_HEIGHT/2+100):b<CANVAS_WIDTH/2?(y.gotoAndStop("cloud1"),y.x=CANVAS_WIDTH/2-350,y.y=CANVAS_HEIGHT/2-30):(y.gotoAndStop("cloud2"),y.x=CANVAS_WIDTH/2+350,y.y=CANVAS_HEIGHT/2-200),s_oStage.addChild(y),(new createjs.Tween.get(y)).to({alpha:1,scaleX:1,scaleY:1},300,createjs.Ease.bounceOut).wait(1500).to({scaleX:.1,scaleY:.1},300,createjs.Ease.cubicIn).to({alpha:0},20).call(function(){s_oStage.removeChild(y)}))};
this.onMouseOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.init()}
function CGame(a){var d,b=0,c,g=null,h,e=[],l,f,p,m=!1,n,q,y,w,x,z,A,r,D,I,J,O,F;this._init=function(){d=1E5;O=-(STARTING_NUM_CARDS-1);w=z=I=!1;f=new CTurnManager;J=[];J[0]=TEXT_PLAYER_1;J[1]=TEXT_PLAYER_2;J[2]=TEXT_PLAYER_3;J[3]=TEXT_PLAYER_4;n=new CAnimation;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);c=new CInterface;!0===s_bFirstGame?new CPanelTutorial:this.startGame();setVolume("soundtrack",.4)};this.startGame=function(){D=new createjs.Container;var a={images:[s_oSpriteLibrary.getSprite("finger")],
frames:{width:202,height:277,regX:101,regY:138.5},animations:{idle:{frames:[0,1,2,3,4,5,6,7,8,9],speed:.9}}};a=new createjs.SpriteSheet(a);y=new createjs.Sprite(a,"idle");y.scaleX=.5;y.scaleY=.5;y.x=CANVAS_WIDTH/2-90;y.y=CANVAS_HEIGHT/2-100;r=new createjs.Container;for(a=0;a<NUM_PLAYERS;a++){var b=0,c=0;aHandPos["num_player_"+NUM_PLAYERS][a].x===CANVAS_WIDTH/2?b=CARD_WIDTH/2:c=CARD_HEIGHT/4;e[a]=new CHandDisplayer(b,c,aHandPos["num_player_"+NUM_PLAYERS][a].x,aHandPos["num_player_"+NUM_PLAYERS][a].y,
a,r,J[a])}A=new createjs.Container;h=new CDeckDisplayer(CANVAS_WIDTH/2,CANVAS_HEIGHT/2,A);l=new CDeckDisplayer(CANVAS_WIDTH/2+CARD_WIDTH,CANVAS_HEIGHT/2,A);l.disableInputDraw();h.initializeDeck();h.shuffle();h.getContainer().on("mouseover",this.onMouseOverDeck);D.addChild(A);D.addChild(r);s_oStage.addChild(D);this.getFirstHand();F=new createjs.Text(TEXT_ALERT_1,"22px "+PRIMARY_FONT,"#FFFFFF");F.x=CANVAS_WIDTH/2+290;F.y=CANVAS_HEIGHT/2+20;F.textAlign="left";F.lineWidth=250;F.alpha=0;s_oStage.addChild(F)};
this.getFirstHand=function(){var a=h.takeLastCard(),b=f.checkTurn(),c=e[b].getContainerPos();b=e[b].getPosNewCard();var d=h.getGlobalPosition();a.setOnTop();D.addChildAt(A,D.numChildren);h.setOnTop();a.moveCardFirstHand(c.x+b.x-d.x,c.y+b.y-d.y,250)};this.onCardDealed=function(a){var b=f.checkTurn();e[b].pushCard(new CCard(e[b].getPosNewCard().x,e[b].getPosNewCard().y,e[b].getContainer(),a.getFotogram(),a.getRank(),a.getSuit()));a.unload();a=e[b].getLastCard();e[b].centerContainer();0===b&&a.showCardNoInput(0,
"mute");f.nextTurn();e[e.length-1].getLength()<STARTING_NUM_CARDS?this.getFirstHand():(D.addChildAt(A,D),h.setOnTop(),a=h.takeFirstLastCard(),a.moveFirstLastCard(CARD_WIDTH,0,600),c.setOnTop())};this.onFirstLastCardDealed=function(a){l.pushCard(new CCard(0,0,l.getContainer(),a.getFotogram(),a.getRank(),a.getSuit()));a.unload();a=l.getLastCard();a.showCardNoInput();h.moveContainer(CANVAS_WIDTH/2-CARD_WIDTH/2,CANVAS_HEIGHT/2,400);l.moveContainer(CANVAS_WIDTH/2+CARD_WIDTH/2,CANVAS_HEIGHT/2,400);p=l.getLastCard().getSuit();
c.refreshColor(p);f.setTurn(Math.floor(Math.random()*NUM_PLAYERS)+0);var b=f.checkTurn();e[b].setOnTurn(b);l.disableInputUsedCards();this.applyEffectOnCard(a,!0)};this.pickCard=function(a,b){O++;var c=l.getLastCard(),d=f.checkTurn(),g=e[d].getContainerPos(),h=l.getGlobalPosition();D.addChildAt(r,D.numChildren);e[d].setOnTop();0===d&&(a.getRank()===c.getRank()&&"draw_four"!==a.getFotogram()||a.getSuit()===p||"color"===a.getFotogram()?(this.offInputPlayer(),a.moveCard(h.x-g.x,h.y-g.y,300),playSound("card",
1,!1),2===e[0].getLength()&&(m=!0)):14===a.getRank()&&!0===this.checkAvaiableDrawFour()&&(this.offInputPlayer(),a.moveCard(h.x-g.x,h.y-g.y,300),playSound("card",1,!1),2===e[0].getLength()&&(m=!0)))};this.cpuPickCard=function(a){var b=f.checkTurn(),c=e[b].getContainerPos(),d=l.getGlobalPosition();D.addChildAt(r,D.numChildren);e[b].setOnTop();a.moveCard(d.x-c.x,d.y-c.y,400,1E3);h.setChildDepth(2);l.setChildDepth(2);a.showCard(1E3)};this.playedCard=function(a){var b=f.checkTurn(),d=e[b].searchIndexCard(a);
l.pushCard(new CCard(0,0,l.getContainer(),a.getFotogram(),a.getRank(),a.getSuit()));l.disableInputUsedCards();l.getLastCard().instantShow();e[b].removeCardByIndex(d);a.unload();0!==b&&e[b].checkUno();4!==l.getLastCard().getSuit()&&(p=l.getLastCard().getSuit(),c.refreshColor(p));e[b].organizeHand(d);this.applyEffectOnCard(a)};this.applyEffectOnCard=function(a,b){var d=this;b||(b=!1);if(!0===b){q=f.checkTurn();f.prevTurn();var e=f.checkTurn()}else e=f.checkTurn(),q=f.checkNextPlayer();if("color"===
a.getFotogram())0===e?(!0===m?new CSelectColorPanel(a.getFotogram(),!0):new CSelectColorPanel(a.getFotogram()),f.nextTurn()):(p=this.onSelectColorCpu(e),f.nextTurn(),n.changeColor(p));else if("draw_four"===a.getFotogram())0===e?!0===m?new CSelectColorPanel(a.getFotogram(),!0):new CSelectColorPanel(a.getFotogram()):(p=this.onSelectColorCpu(e),c.refreshColor(p),n.drawFourAnim());else if("color"!==a.getFotogram()&&"draw_four"!==a.getFotogram()&&a.getSuit()===p||a.getRank()===l.getLastCard().getRank())if(10===
a.getRank())f.nextTurn(),f.nextTurn(),!0===m?setTimeout(function(){!0===m&&d.drawCards(0,2,0,!0);setTimeout(function(){n.stopTurn()},800)},2E3):n.stopTurn();else if(11===a.getRank())2<NUM_PLAYERS?(f.changeClockWise(),!0!==b?f.nextTurn():f.prevTurn()):(f.changeClockWise(),f.nextTurn(),f.nextTurn()),!0===m?setTimeout(function(){!0===m&&d.drawCards(0,2,0,!0);setTimeout(function(){n.changeClockWise(f.getClockWise())},1E3)},2E3):n.changeClockWise(f.getClockWise());else if(12===a.getRank())!0===m?setTimeout(function(){!0===
m&&d.drawCards(0,2,0,!0);setTimeout(function(){n.drawTwoAnim()},1E3)},2E3):n.drawTwoAnim();else if(10>a.getRank())if(f.nextTurn(),!0===m)setTimeout(function(){if(!0===m)d.drawCards(0,2,0,!0);else d.onNextTurn()},2E3);else this.onNextTurn()};this.onNextTurn=function(){if(!0!==this.checkGameOver())if(0===h.getLength()&&!1===I)I=!0,n.shuffleAnimation();else{this.setOffTurn();h.enableInputDraw();var a=f.checkTurn();e[a].setOnTurn(a);var b=l.getLastCard();if(0===a)this.onInputPlayer(),!0===this.onCheckDraw()&&
this.checkHelpDraw();else if(0!==a){var c=[];for(var d=0;d<e[a].getLength();d++)4===e[a].getCardByIndex(d).getSuit()||e[a].getCardByIndex(d).getRank()!==b.getRank()&&e[a].getCardByIndex(d).getSuit()!==p?"color"===e[a].getCardByIndex(d).getFotogram()?c.push({oCard:e[a].getCardByIndex(d),iValue:2}):"draw_four"===e[a].getCardByIndex(d).getFotogram()&&c.push({oCard:e[a].getCardByIndex(d),iValue:1}):12===e[a].getCardByIndex(d).getRank()?c.push({oCard:e[a].getCardByIndex(d),iValue:6}):10===e[a].getCardByIndex(d).getRank()?
c.push({oCard:e[a].getCardByIndex(d),iValue:5}):11===e[a].getCardByIndex(d).getRank()?c.push({oCard:e[a].getCardByIndex(d),iValue:4}):c.push({oCard:e[a].getCardByIndex(d),iValue:3});0===c.length?this.drawCards(a,1,1E3):(c.sort(function(a,b){return parseFloat(b.iValue)-parseFloat(a.iValue)}),this.cpuPickCard(c[0].oCard))}}};this.checkAvaiableDrawFour=function(){for(var a=!0,b,c=0;c<e[0].getLength();c++)if(b=e[0].getCardByIndex(c),b.getRank()===l.getLastCard().getRank()&&"draw_four"!==b.getFotogram()||
b.getSuit()===p||"color"===b.getFotogram())a=!1;return a};this.declareUNO=function(){!0===m&&(m=!1,e[0].checkUno())};this.drawCards=function(a,c,d,e){e&&(m=!1,(new createjs.Tween.get(F)).to({alpha:1},400).wait(4E3).to({alpha:0},400));b=c;this.drawCardsTween(a,c,d,e)};this.drawCardsTween=function(a,c,d,g){var m=this,t;D.addChildAt(A,D.numChildren);h.setOnTop();if(0===h.getLength()&&!1===I)I=!0,n.shuffleAnimation(a,c,d);else if(1===c){var r=l.getLastCard();t;var q=h.takeLastCard();q.setOnTop();var w=
e[a].getContainerPos();var x=e[a].getPosNewCard();var y=h.getGlobalPosition();(new createjs.Tween.get(q.getSprite())).wait(d).to({x:w.x+x.x-y.x,y:w.y+x.y-y.y},400,createjs.Ease.cubicOut).call(function(){e[a].pushCard(new CCard(e[a].getPosNewCard().x,e[a].getPosNewCard().y,e[a].getContainer(),q.getFotogram(),q.getRank(),q.getSuit()));q.unload();t=e[a].getLastCard();0===a?(t.showCard(),t.onSetTurned()):playSound("card",1,!1);e[a].centerContainer();t.getRank()===r.getRank()||t.getSuit()===p||"color"===
t.getFotogram()||"draw_four"===t.getFotogram()?0!==a&&(m.onNextTurn(),playSound("card",1,!1)):(e[a].centerContainer(),f.nextTurn(),m.onNextTurn())})}else r=l.getLastCard(),t,q=h.takeLastCard(),q.setOnTop(),w=e[a].getContainerPos(),x=e[a].getPosNewCard(),y=h.getGlobalPosition(),(new createjs.Tween.get(q.getSprite())).wait(d).to({x:w.x+x.x-y.x,y:w.y+x.y-y.y},400,createjs.Ease.cubicOut).call(function(){e[a].pushCard(new CCard(e[a].getPosNewCard().x,e[a].getPosNewCard().y,e[a].getContainer(),q.getFotogram(),
q.getRank(),q.getSuit()));q.unload();t=e[a].getLastCard();0===a?(t.showCard(),t.onSetTurned()):playSound("card",1,!1);e[a].centerContainer();b--;0<b?m.drawCardsTween(a,c,d,g):(g||(f.nextTurn(),f.nextTurn()),m.onNextTurn())})};this.onDraw=function(){h.disableInputDraw();w=!1;s_oStage.removeChild(y);var a=!0;if(0!==l.getLength()&&0===f.checkTurn()){for(var b=0;b<e[0].getLength();b++){var c=e[0].getCardByIndex(b);if(c.getRank()===l.getLastCard().getRank()||c.getSuit()===p||"color"===c.getFotogram()||
"draw_four"===c.getFotogram())a=!1}!0===a&&(this.drawCards(0,1),z=!1)}};this.onCheckDraw=function(){var a=!0;w=!0;if(0!==l.getLength()&&0===f.checkTurn()){for(var b=0;b<e[0].getLength();b++){var c=e[0].getCardByIndex(b);if(c.getRank()===l.getLastCard().getRank()||c.getSuit()===p||"color"===c.getFotogram()||"draw_four"===c.getFotogram())w=a=!1}z=!0===w&&0===f.checkTurn()?!0:!1;return a}};this.onSelectColor=function(a){p=a;c.refreshColor(p)};this.onInputPlayer=function(){for(var a=0;a<e[0].getLength();a++)e[0].getCardByIndex(a).onSetTurned()};
this.offInputPlayer=function(){for(var a=0;a<e[0].getLength();a++)e[0].getCardByIndex(a).offSetTurned()};this.onSelectColorCpu=function(a){for(var b,c=[{iColor:0,iPoints:0},{iColor:1,iPoints:0},{iColor:2,iPoints:0},{iColor:3,iPoints:0}],d=0;d<e[a].getLength();d++){b=e[a].getCardByIndex(d);for(var f=0;f<c.length;f++)b.getSuit()===f&&c[f].iPoints++}c.sort(function(a,b){return parseFloat(b.iPoints)-parseFloat(a.iPoints)});return c[0].iColor};this.onEndDrawFour=function(){this.drawCards(q,4,0)};this.onEndDrawTwo=
function(){this.drawCards(q,2,0)};this.getbUNO=function(){return m};this.checkGameOver=function(){var a=!1;0===e[0].getLength()&&(this.gameOver(0),a=!0);0===e[1].getLength()&&(this.gameOver(1),a=!0);e[2]&&0===e[2].getLength()&&(this.gameOver(2),a=!0);e[3]&&0===e[3].getLength()&&(this.gameOver(3),a=!0);return a};this.setOffTurn=function(){for(var a=0;a<NUM_PLAYERS;a++)e[a].setOffTurn(a)};this.checkNumOfCards=function(){if(0===h.getLength()){var a=l.removeAllCardUnderTheDeck();this.shuffle(a);for(var b=
0;b<a.length;b++)h.pushCard(new CCard(0,0,h.getContainer(),a[b].getFotogram(),a[b].getRank(),a[b].getSuit())),a[b].unload();I=!1}};this.onEndShuffle=function(a,c,d){this.checkNumOfCards();if(0!==b)this.drawCardsTween(a,c,d);else this.onNextTurn()};this.shuffle=function(a){var b;for(b=a.length;b;b--){var c=Math.floor(Math.random()*b);var d=a[b-1];a[b-1]=a[c];a[c]=d}};this.unload=function(){null!==g&&g.unload();c.unload();w=!1;createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=
function(){$(s_oMain).trigger("end_session");s_oGame.unload();s_oMain.gotoMenu()};this.stopFinger=function(){!0===w&&(w=!1)};this.gameOver=function(a){x=new createjs.Shape;x.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);x.alpha=0;x.on("mousedown",function(){});s_oStage.addChild(x);(new createjs.Tween.get(x)).to({alpha:.7},500);d=0===a?Math.floor(1/O*d):0;g=CEndPanel(s_oSpriteLibrary.getSprite("credits_panel"));g.show(d,a)};this.checkHelpDraw=function(){setTimeout(function(){!0===
w&&s_oStage.addChildAt(y,s_oStage.numChildren)},5E3)};this.onMouseOverDeck=function(a){s_bMobile||(a.target.cursor=!0===z?"pointer":"default")};this.update=function(){};s_oGame=this;STARTING_NUM_CARDS=a.starting_num_cards;this._init()}var s_oGame;
function CInterface(){var a,d,b,c,g,h,e,l,f,p,m,n,q,y,w=null,x=null,z,A;this._init=function(){A=new createjs.Container;var r=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-r.height/2-10;l=r.height/2+10;n=new CGfxButton(e,l,r,A);n.addEventListener(ON_MOUSE_UP,this._onExit,this);g=CANVAS_WIDTH-r.width/2-100;h=r.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r=s_oSpriteLibrary.getSprite("audio_icon"),m=new CToggle(g,h,r,s_bAudioActive,A),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);r=window.document;var D=r.documentElement;w=D.requestFullscreen||D.mozRequestFullScreen||D.webkitRequestFullScreen||D.msRequestFullscreen;x=r.exitFullscreen||r.mozCancelFullScreen||r.webkitExitFullscreen||r.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(w=!1);w&&screenfull.enabled&&(r=s_oSpriteLibrary.getSprite("but_fullscreen"),b=r.width/4+10,c=r.height/2+10,q=new CToggle(b,c,r,s_bFullscreen,A),q.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));r=s_oSpriteLibrary.getSprite("but_uno");a=CANVAS_WIDTH/
2+222;d=CANVAS_HEIGHT/2+70;z=new CGfxButton(a,d,r,s_oStage);z.addEventListener(ON_MOUSE_UP,this._onButUno,this);r=s_oSpriteLibrary.getSprite("colors");r=new createjs.SpriteSheet({images:[r],frames:{width:103,height:102,regX:51.5,regY:51},animations:{red:[0],green:[1],blue:[2],yellow:[3]}});f=CANVAS_WIDTH/2+220;p=CANVAS_HEIGHT/2-60;y=new createjs.Sprite(r,0);y.stop();y.x=f;y.y=p;s_oStage.addChild(A);this.refreshButtonPos()};this.setButtonUno=function(a){z.setClickable(a)};this.refreshColor=function(a){y.gotoAndStop(a);
s_oStage.addChildAt(y,1)};this._onButUno=function(){s_oGame.declareUNO()};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;n.unload();w&&screenfull.enabled&&q.unload();s_oInterface=null};this.refreshButtonPos=function(){n.setPosition(e-s_iOffsetX,s_iOffsetY+l);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(g-s_iOffsetX,s_iOffsetY+h);w&&screenfull.enabled&&q.setPosition(b+s_iOffsetX,c+s_iOffsetY)};this.setOnTop=function(){s_oStage.addChildAt(A,s_oStage.numChildren)};
this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){new CAreYouSurePanel(s_oGame.onExit)};this.resetFullscreenBut=function(){w&&screenfull.enabled&&q.setActive(s_bFullscreen)};this._onFullscreen=function(){s_bFullscreen?x.call(window.document):w.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,d,b,c,g,h;this._init=function(){var e=this;g=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));var f=CANVAS_WIDTH/2,p=CANVAS_HEIGHT/2-200;d=new createjs.Text(TEXT_HELP1," 24px Arial","#000000");d.x=f+2;d.y=p+2;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=400;a=new createjs.Text(TEXT_HELP1," 24px Arial","#ffffff");a.x=f;a.y=p;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=400;f=CANVAS_WIDTH/2-130;p=CANVAS_HEIGHT/2-40;c=new createjs.Text(TEXT_HELP2,
" 24px Arial","#000000");c.x=f+2;c.y=p+2;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=280;b=new createjs.Text(TEXT_HELP2," 24px Arial","#ffffff");b.x=f;b.y=p;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=280;h=new createjs.Container;h.addChild(g,d,a,c,b);h.alpha=0;s_oStage.addChild(h);createjs.Tween.get(h).to({alpha:1},700);h.on("pressup",function(){e._onExitHelp()})};this.unload=function(){s_oStage.removeChild(h);var a=this;h.off("pressup",function(){a._onExitHelp()})};
this._onExitHelp=function(){e.unload();s_oGame._onExitHelp()};var e=this;this._init()}
function CCreditsPanel(){var a,d,b,c,g;this._init=function(){d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;d.on("mousedown",function(){});s_oStage.addChild(d);(new createjs.Tween.get(d)).to({alpha:.7},500);b=new createjs.Container;s_oStage.addChild(b);var h=s_oSpriteLibrary.getSprite("credits_panel"),e=createBitmap(h);e.regX=h.width/2;e.regY=h.height/2;b.addChild(e);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT+h.height/2;a=b.y;(new createjs.Tween.get(b)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);e=new createjs.Text("DEVELOPED BY"," 20px "+PRIMARY_FONT,"#ffffff");e.y=-h.height/2+40;e.textAlign="center";e.textBaseline="middle";e.lineWidth=300;b.addChild(e);h=new createjs.Text("www.codethislab.com"," 30px "+PRIMARY_FONT,"#ffffff");h.y=100;h.textAlign="center";h.textBaseline="middle";h.lineWidth=500;b.addChild(h);h=s_oSpriteLibrary.getSprite("ctl_logo");g=createBitmap(h);g.on("click",this._onLogoButRelease);g.regX=h.width/2;g.regY=h.height/2;b.addChild(g);h=s_oSpriteLibrary.getSprite("but_exit");
c=new CGfxButton(230,-107,h,b);c.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){c.setClickable(!1);(new createjs.Tween.get(d)).to({alpha:0},500);(new createjs.Tween.get(b)).to({y:a},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(d);s_oStage.removeChild(b);c.unload()});d.off("mousedown",function(){});g.off("mousedown",this._onLogoButRelease)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
function CSelectColorPanel(a,d){var b,c,g,h,e=this,l,f,p,m;this._init=function(){"color"===a&&playSound("special_card",.5,!1);e=this;c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;c.on("mousedown",function(){});s_oStage.addChild(c);(new createjs.Tween.get(c,{override:!0})).to({alpha:.7},500);g=new createjs.Container;s_oStage.addChild(g);h=new createjs.Container;g.addChild(h);var d=s_oSpriteLibrary.getSprite("select_color_panel"),q=createBitmap(d);
q.regX=d.width/2;q.regY=d.height/2;g.addChildAt(q,0);g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT+d.height/2;b=g.y;(new createjs.Tween.get(g,{override:!0})).to({y:CANVAS_HEIGHT/2-40},600,createjs.Ease.backOut);q=new createjs.Text(TEXT_SELECT_COLOR," 45px "+PRIMARY_FONT,"#ffffff");q.y=-d.height/2+90;q.textAlign="center";q.textBaseline="middle";q.lineWidth=400;g.addChild(q);h.y=g.getBounds().height/5;d=s_oSpriteLibrary.getSprite("but_red");l=new CGfxButton(-190,-20,d,h);l.addEventListener(ON_MOUSE_UP,function(){e.onSelectColor(0);
h});d=s_oSpriteLibrary.getSprite("but_green");f=new CGfxButton(-65,-20,d,h);f.addEventListener(ON_MOUSE_UP,function(){e.onSelectColor(1);h});d=s_oSpriteLibrary.getSprite("but_blue");p=new CGfxButton(65,-20,d,h);p.addEventListener(ON_MOUSE_UP,function(){e.onSelectColor(2);h});d=s_oSpriteLibrary.getSprite("but_yellow");m=new CGfxButton(190,-20,d,h);m.addEventListener(ON_MOUSE_UP,function(){e.onSelectColor(3);h})};this.onSelectColor=function(a){s_oGame.onSelectColor(a);e.unload()};this.unload=function(){"color"===
a?((new createjs.Tween.get(c,{override:!0})).to({alpha:0},500),(new createjs.Tween.get(g,{override:!0})).to({y:b},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(c,{override:!0});s_oStage.removeChild(g,{override:!0});if(d)setTimeout(function(){if(!0===s_oGame.getbUNO())s_oGame.drawCards(0,2,0,d);else s_oGame.onNextTurn()},2E3);else s_oGame.onNextTurn()})):((new createjs.Tween.get(c,{override:!0})).to({alpha:0},500),(new createjs.Tween.get(g,{override:!0})).to({y:b},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(c);
s_oStage.removeChild(g);d?setTimeout(function(){!0===s_oGame.getbUNO()&&s_oGame.drawCards(0,2,0,d);setTimeout(function(){s_oCAnimation.drawFourAnim()},1E3)},2E3):s_oCAnimation.drawFourAnim()}));c.off("mousedown",function(){})};this._init()}
function CAreYouSurePanel(a){var d,b,c,g,h;this._init=function(a){s_oGame.stopFinger();g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;g.on("mousedown",function(){});s_oStage.addChild(g);(new createjs.Tween.get(g)).to({alpha:.7},500);h=new createjs.Container;s_oStage.addChildAt(h,s_oStage.numChildren);a=s_oSpriteLibrary.getSprite("credits_panel");var e=createBitmap(a);e.regX=a.width/2;e.regY=a.height/2;h.addChild(e);h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT+
a.height/2;d=h.y;(new createjs.Tween.get(h)).to({y:CANVAS_HEIGHT/2-40},500,createjs.Ease.quartIn).call(function(){createjs.Ticker.paused=!0});e=new createjs.Text(TEXT_ARE_SURE," 44px "+PRIMARY_FONT,"#000000");e.y=-a.height/2+95;e.textAlign="center";e.textBaseline="middle";e.lineWidth=400;e.outline=5;h.addChild(e);a=new createjs.Text(TEXT_ARE_SURE," 44px "+PRIMARY_FONT,"#FFFFFF");a.y=e.y;a.textAlign="center";a.textBaseline="middle";a.lineWidth=400;h.addChild(a);b=new CGfxButton(110,80,s_oSpriteLibrary.getSprite("but_yes_big"),
h);b.addEventListener(ON_MOUSE_UP,this._onButYes,this);c=new CGfxButton(-110,80,s_oSpriteLibrary.getSprite("but_exit_big"),h);c.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this._onButYes=function(){c.setClickable(!1);b.setClickable(!1);createjs.Ticker.paused=!1;(new createjs.Tween.get(g)).to({alpha:0},500);(new createjs.Tween.get(h)).to({y:d},400,createjs.Ease.backIn).call(function(){a();e.unload()})};this._onButNo=function(){createjs.Ticker.paused=!1;c.setClickable(!1);b.setClickable(!1);(new createjs.Tween.get(g)).to({alpha:0},
500);(new createjs.Tween.get(h)).to({y:d},400,createjs.Ease.backIn).call(function(){e.unload()})};this.unload=function(){c.unload();b.unload();s_oStage.removeChild(g);s_oStage.removeChild(h);g.off("mousedown",function(){})};var e=this;this._init(a)}
function CEndPanel(a){var d,b,c,g,h,e,l,f,p;this._init=function(a){d=createBitmap(a);a=d.getBounds();d.regX=a.width/2;d.regY=a.height/2;d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2;c=new createjs.Text(""," 50px "+PRIMARY_FONT,"#000");c.x=CANVAS_WIDTH/2+1;c.y=CANVAS_HEIGHT/2-30;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=550;g=new createjs.Text(""," 50px "+PRIMARY_FONT,"#ffffff");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-28;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=550;h=
new createjs.Text(""," 35px "+PRIMARY_FONT,"#000");h.x=CANVAS_WIDTH/2+1;h.y=CANVAS_HEIGHT/2+120;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=550;e=new createjs.Text(""," 35px "+PRIMARY_FONT,"#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+110;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=550;b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(d,h,e,c,g);s_oStage.addChild(b);a=s_oSpriteLibrary.getSprite("but_restart");f=new CGfxButton(CANVAS_WIDTH/2+60,CANVAS_HEIGHT/
2+180,a,b);a=s_oSpriteLibrary.getSprite("but_home");p=new CGfxButton(CANVAS_WIDTH/2-60,CANVAS_HEIGHT/2+180,a,b)};this.unload=function(){};this._initListener=function(){p.addEventListener(ON_MOUSE_DOWN,this._onExit,this);f.addEventListener(ON_MOUSE_DOWN,this._onRestart,this)};this.show=function(a,d){playSound("game_over",1,!1);l=a;var f=d+1;0===d?(c.text=TEXT_GAMEOVER,g.text=TEXT_GAMEOVER,g.y=CANVAS_HEIGHT/2-30,c.y=CANVAS_HEIGHT/2-28):(l=a=0,c.text=TEXT_LOSE+f+TEXT_LOSE2,g.text=TEXT_LOSE+f+TEXT_LOSE2);
h.text=TEXT_SCORE+": "+a;e.text=TEXT_SCORE+": "+a;b.visible=!0;var m=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){m._initListener()});$(s_oMain).trigger("save_score",a);$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this._onExit=function(){$(s_oMain).trigger("share_event",l);b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.unload();s_oMain.gotoMenu()};this._onRestart=function(){s_oGame.unload();s_oMain.gotoGame(!1);s_oStage.removeChild(b)};
this._init(a);return this};