function k(b,a,c,d){b.v.Cb(b.gb,a,c,d,void 0)}function l(b,a,c,d){b.v.ia?k(b,a,c,d):b.v.ve()._OnMessageFromDOM({type:"event",component:b.gb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.D(b.gb,a,c)}function r(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Nb||(b.v.oe(b.Nd),b.Nb=!0)}window.Ga=class{constructor(b,a){this.v=b;this.gb=a;this.Nb=!1;this.Nd=()=>this.Ja()}Zc(){}Ja(){}};function aa(b){-1!==b.Wa&&(self.clearTimeout(b.Wa),b.Wa=-1)}
window.le=class{constructor(b){this.Gc=b;this.Je=5;this.Wa=-1;this.Pb=-Infinity;this.Od=()=>{this.Wa=-1;this.Pb=Date.now();this.lb=!0;this.Gc();this.lb=!1};this.qd=this.lb=!1}j(){aa(this);this.Od=this.Gc=null}};"use strict";function ba(b,a){n(b,"get-element",c=>{const d=b.ga.get(c.elementId);return a(d,c)})}
window.cf=class extends self.Ga{constructor(b,a){super(b,a);this.ga=new Map;this.Fc=!0;r(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=this.ga.get(c);this.Fc&&d.parentElement.removeChild(d);this.ga.delete(c)}],["set-visible",c=>{this.Fc&&(this.ga.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.Fc){var d=this.ga.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=
c.height+"px";c=c.fontSize;null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{this.ga.get(c.elementId);throw Error("required override");}],["focus",c=>this.Ac(c)],["set-css-style",c=>{this.ga.get(c.elementId).style[c.prop]=c.val}],["set-attribute",c=>{this.ga.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.ga.get(c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}Ac(b){var a=this.ga.get(b.elementId);b.focus?a.focus():a.blur()}};"use strict";
const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent);let da=0;function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Te?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.Xe+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;
function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let x=new Audio;const ia={"audio/webm; codecs=opus":!!x.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!x.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!x.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!x.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!x.canPlayType("audio/mp4"),"audio/mpeg":!!x.canPlayType("audio/mpeg")};x=null;
async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let A=0;window.RealFile=window.File;const B=[],D=new Map,E=new Map;let la=0;const ma=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ma.push(b)};const na=new Set(["cordova","playable-ad","instant-games"]);
let oa=!1;
window.qa=class b{constructor(a){this.ia=a.Ze;this.ua=null;this.aa="";this.dc=a.We;this.zb={};this.Pa=this.yb=null;this.Lb=[];this.H=this.Ua=null;this.Oc=!1;this.td=0;this.nb=null;this.Ta=-1;this.Oe=()=>this.Ce();this.Sa=[];this.A=a.Pd;this.Ob="file"===location.protocol.substr(0,4);!this.ia||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.ia=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ia=!1;if("cordova"===this.A&&this.ia)if(v){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.ia=!1)}else this.ia=!1;this.Sb=this.ma=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("runtime","cordova-fetch-local-file",c=>this.ye(c));this.D("runtime","create-job-worker",()=>this.ze());"cordova"===this.A?document.addEventListener("deviceready",()=>this.jd(a)):this.jd(a)}j(){this.sc();
this.ua&&(this.ua=this.ua.onmessage=null);this.yb&&(this.yb.terminate(),this.yb=null);this.Pa&&(this.Pa.j(),this.Pa=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}ie(){return ca&&"cordova"===this.A}oc(){const a=navigator.userAgent;return ca&&na.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ge(){return v}dd(){return v&&na.has(this.A)}async jd(a){"macos-wkwebview"===this.A&&this.Dc({type:"ready"});if("playable-ad"===this.A){this.ma=self.c3_base64files;
this.Sb={};await this.re();for(let d=0,e=a.Xa.length;d<e;++d){var c=a.Xa[d].toLowerCase();this.Sb.hasOwnProperty(c)?a.Xa[d]={Te:!0,Xe:this.Sb[c]}:this.ma.hasOwnProperty(c)&&(a.Xa[d]=URL.createObjectURL(this.ma[c]))}}a.Ve?this.aa=a.Ve:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.af&&(this.zb=a.af);c=new MessageChannel;this.ua=c.port1;this.ua.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.Be(d));this.nb=new self.je(this);await pa(this.nb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ia?await this.xe(a,c.port2):await this.we(a,c.port2)}uc(a){a=this.zb.hasOwnProperty(a)?this.zb[a]:a.endsWith("/workermain.js")&&this.zb.hasOwnProperty("workermain.js")?
this.zb["workermain.js"]:"playable-ad"===this.A&&this.ma.hasOwnProperty(a.toLowerCase())?this.ma[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async jc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Ob)return a=await this.Ab(d.Se?a:this.dc+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");
a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}sa(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}hd(a){var c=this.aa,d=location.href,e=this.sa(),f=this.ja(),g=window.devicePixelRatio,h=b.bb(),m=a.hf,p=window.cr_previewImageBlobs||this.ma,q=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,y=window.ff||"";a=a.Pd;var W=(new URLSearchParams(self.location.search)).has("debug"),C=this.nb;return{runtimeBaseUrl:c,previewUrl:d,
windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:t,swClientId:y,exportType:a,isDebug:W,ife:!!self.gf,jobScheduler:{inputPort:C.Nc,outputPort:C.Tc,maxNumWorkers:C.Le},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.dc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.dc+"opus.wasm.wasm",isFileProtocol:this.Ob,isiOSCordova:this.ie(),isiOSWebView:this.oc(),
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async xe(a,c){var d=this.uc(a.$e);this.yb=await this.jc(d,this.aa,{type:"module",name:"Runtime",Se:!0});this.H=document.createElement("canvas");this.H.style.display="none";d=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.Yc||[],f=a.Xa;e=await Promise.all(e.map(g=>this.Ka(g)));f=await Promise.all(f.map(g=>this.Ka(g)));if("cordova"===
this.A)for(let g=0,h=a.hc.length;g<h;++g){const m=a.hc[g],p=m[0];if(p===a.Wc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))m[1]=await this.Ka(p)}this.yb.postMessage(Object.assign(this.hd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,workerDependencyScripts:e,engineScripts:f,projectScripts:a.hc,mainProjectScript:a.Wc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...ra(this.nb)]);this.Lb=B.map(g=>new g(this));this.gd();self.c3_callFunction=(g,h)=>{var m=this.Ua;
return m.v.fd(m.gb,"js-invoke-function",{name:g,params:h},void 0,void 0)};"preview"===this.A&&(self.goToLastErrorScript=()=>this.Cb("runtime","go-to-last-error-script"))}async we(a,c){this.H=document.createElement("canvas");this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Lb=B.map(g=>new g(this));this.gd();var d=a.Xa.map(g=>"string"===typeof g?(new URL(g,this.aa)).toString():g);Array.isArray(a.Yc)&&
d.unshift(...a.Yc);d=await Promise.all(d.map(g=>this.Ka(g)));await Promise.all(d.map(g=>w(g)));d=self.C3_ProjectScriptsStatus;const e=a.Wc,f=a.hc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ka(h),await w(h),"preview"!==this.A||d[g]||this.ld(g,"main script did not run to completion")}catch(m){this.ld(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ka(h),await w(h);"preview"===this.A&&"object"!==typeof self.bf.df?(this.Gb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.hd(a),{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:ma}),this.kd(),this.Pa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Pa,a))}ld(a,c){this.Gb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}kd(){this.Gb()}Gb(){const a=
window.Qe;a&&(a.parentElement.removeChild(a),window.Qe=null)}async ze(){const a=await sa(this.nb);return{outputPort:a,transferables:[a]}}ve(){if(this.ia)throw Error("not available in worker mode");return this.Pa}Cb(a,c,d,e,f){this.ua.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}fd(a,c,d,e,f){const g=la++,h=new Promise((m,p)=>{E.set(g,{resolve:m,reject:p})});this.ua.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ae(a);if("result"===c)this.De(a);else if("runtime-ready"===c)this.Ee();else if("alert-error"===c)this.Gb(),alert(a.message);else if("creating-runtime"===c)this.kd();else throw Error(`unknown message '${c}'`);}Ae(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=D.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Fb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Fb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Fb(f,!1,""+h)}):this.Fb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Fb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.ua.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}De(a){const c=a.responseId,d=a.isOk;a=a.result;const e=E.get(c);d?e.resolve(a):e.reject(a);E.delete(c)}D(a,
c,d){let e=D.get(a);e||(e=new Map,D.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ya(a){if(B.includes(a))throw Error("DOM handler already added");B.push(a)}gd(){for(const a of this.Lb)if("runtime"===a.gb){this.Ua=a;return}throw Error("cannot find runtime DOM handler");}Be(a){this.Cb("debugger","message",a)}Ee(){for(const a of this.Lb)a.Zc()}static bb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
oa)}static Hb(a){oa=!!a}oe(a){this.Sa.push(a);this.Cc()}Ge(a){a=this.Sa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Sa.splice(a,1);this.Sa.length||this.sc()}Cc(){-1===this.Ta&&this.Sa.length&&(this.Ta=requestAnimationFrame(this.Oe))}sc(){-1!==this.Ta&&(cancelAnimationFrame(this.Ta),this.Ta=-1)}Ce(){this.Ta=-1;for(const a of this.Sa)a();this.Cc()}ya(a){this.Ua.ya(a)}Ia(a){this.Ua.Ia(a)}Bc(){this.Ua.Bc()}Eb(a){this.Ua.Eb(a)}he(){return!!ia["audio/webm; codecs=opus"]}async He(a){a=await this.fd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}me(a){this.Oc=!0;this.td=a}fe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ed(a){return!this.fe(a)}async Ka(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Ob&&this.ed(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Ab(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async ye(a){const c=a.filename;switch(a.as){case "text":return await this.ee(c);
case "buffer":return await this.Ab(c);default:throw Error("unsupported type");}}bd(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ee(a){a=await this.bd(a);return await ja(a)}tc(){if(z.length&&!(8<=A)){A++;var a=z.shift();this.se(a.filename,a.Ye,a.Re)}}Ab(a){return new Promise((c,d)=>{z.push({filename:a,Ye:e=>{A--;this.tc();c(e)},Re:e=>{A--;this.tc();d(e)}});this.tc()})}async se(a,
c,d){try{const e=await this.bd(a),f=await ka(e);c(f)}catch(e){d(e)}}Dc(a){if("windows-webview2"===this.A)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.A)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async re(){const a=[];for(const [c,d]of Object.entries(this.ma))a.push(this.qe(c,d));await Promise.all(a)}async qe(a,c){if("object"===typeof c)this.ma[a]=new Blob([c.str],{type:c.type}),this.Sb[a]=
c.str;else{let d=await this.ue(c);d||(d=this.te(c));this.ma[a]=d}}async ue(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}te(a){a=this.Fe(a);return this.pe(a.data,a.Ue)}Fe(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);
c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ue:a,data:d}}pe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const F=self.qa;
function ta(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),G={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},H={dispatchRuntimeEvent:!0};
function wa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function xa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function I(b){b=URL.createObjectURL(b);try{return await xa(b)}finally{URL.revokeObjectURL(b)}}
function ya(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function za(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await I(b);var d=await ya(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await I(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await I(b)}
function J(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Aa=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);function K(b){Ba.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ca(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await I(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await za(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let L=!1;document.addEventListener("pause",()=>L=!0);document.addEventListener("resume",()=>L=!1);async function Da(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ea(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ha(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ia(b){self.setTimeout(()=>{b.sd=!0},1E3);"cordova"===b.v.A?(document.addEventListener("pause",()=>Ja(b,!0)),document.addEventListener("resume",()=>Ja(b,!1))):document.addEventListener("visibilitychange",()=>Ja(b,document.hidden));return{isSuspended:!(!document.hidden&&!L)}}
function Ka(b){b.nd||(b.nd=!0,window.addEventListener("deviceorientation",a=>{b.Y||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},G)}),window.addEventListener("deviceorientationabsolute",a=>{b.Y||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},G)}))}
function La(b){b.md||(b.md=!0,window.addEventListener("devicemotion",a=>{if(!b.Y){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},G)}}))}async function Ma(b){await wa(b.url)}
function Na(b,a){b.ud=a.message;-1===b.Jc&&(b.Jc=setTimeout(()=>{b.Jc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.ud)},250))}function M(b){if(!b.Y){var a=F.bb();a&&"any"!==b.Uc&&Oa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.sa(),innerHeight:b.ja()})}}function Pa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:F.bb(),innerWidth:b.sa(),innerHeight:b.ja()})}
function Ja(b,a){a?b.v.sc():b.v.Cc();k(b,"visibilitychange",{hidden:a})}function Qa(b,a,c){"Backspace"===c.key&&K(c);if(!b.Y){var d=ua.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},G)}}
function Ra(b,a,c,d){b.Y||ta(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Z,pageX:c.pageX,pageY:c.pageY+b.Z,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Sa(b){window!==window.top&&window.focus();Ta(b.target)&&document.activeElement&&!Ta(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.Y){if(b.vb&&"pointermove"!==a){var d=b.vb;d.lb||(aa(d),d.Pb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.sb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Z,pageX:c.pageX,pageY:c.pageY+b.Z,movementX:(c.movementX||0)+b.Zb,movementY:(c.movementY||0)+b.$b,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},G);b.Zb=0;b.$b=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Ra(b,d,c,va),b.sb=c.buttons)}}
function Ua(b,a,c){if(!b.Y&&!ta(c)){var d=b.sb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Z,pageX:c.pageX,pageY:c.pageY+b.Z,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},G);b.sb=c.buttons;Ra(b,c.type,c,va)}}
function O(b,a,c){if(!b.Y)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.Z,pageX:f.pageX,pageY:f.pageY+b.Z,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
G)}}function Va(b,a,c){document.body.style.transform="";b.Z=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.Z=a))}}function Wa(b,a,c,d){const e=b.sa(),f=b.ja();b.Va=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.bb()}):10>d&&Xa(b,e,f,d+1)}
function Xa(b,a,c,d){-1!==b.Va&&clearTimeout(b.Va);b.Va=setTimeout(()=>Wa(b,a,c,d),48)}
function Oa(b){b=b.Uc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ta(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
F.Ya(class extends self.Ga{constructor(b){super(b,"runtime");this.zd=!0;this.Va=-1;this.Uc="any";this.md=this.nd=!1;this.Ba=null;this.Y=!1;this.ud="";this.Jc=-1;this.Oa=this.vb=null;this.$b=this.Zb=0;this.sd=!1;this.Dd=b.sa();this.Qb=b.ja();this.Z=this.xb=0;b.D("canvas","update-size",d=>{var e=this.v;e.Oc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.zd&&(e.style.display="",this.zd=!1))});b.D("runtime",
"invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.D("runtime","raster-svg-image",d=>Da(d));b.D("runtime","get-svg-image-size",d=>Ea(d));b.D("runtime","set-target-orientation",d=>{this.Uc=d.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime","post-to-debugger",d=>Ha(d));b.D("runtime","go-to-script",d=>
Ha(d));b.D("runtime","before-start-ticking",()=>Ia(this));b.D("runtime","debug-highlight",d=>{if(d.show){this.Ba||(this.Ba=document.createElement("div"),this.Ba.id="inspectOutline",document.body.appendChild(this.Ba));var e=this.Ba;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ba&&(this.Ba.style.display="none")});b.D("runtime","enable-device-orientation",()=>Ka(this));b.D("runtime","enable-device-motion",
()=>La(this));b.D("runtime","add-stylesheet",d=>Ma(d));b.D("runtime","alert",d=>this.xc(d));b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",d=>{this.Y=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.H.style.display="";this.v.me(d.duration)});b.D("runtime","export-to-video-progress",
d=>Na(this,d));b.D("runtime","exported-to-video",d=>{window.Pe({type:"exported-video",blob:d.blob,time:d.time})});b.D("runtime","exported-to-image-sequence",d=>{window.Pe({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||J(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",
K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.sb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",
()=>{a:{if(!this.Y){var d=this.sa();var e=this.ja();if(this.v.dd()){if(this.sd){if(this.Dd===d&&e<this.Qb){this.xb=this.Qb-e;Va(this,this.Qb,this.xb);d=void 0;break a}0<this.xb&&(this.xb=0,Va(this,e,this.xb))}this.Dd=d;this.Qb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.bb()});this.v.oc()&&(-1!==this.Va&&clearTimeout(this.Va),Wa(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",
()=>M(this));window.addEventListener("mozfullscreenchange",()=>M(this));window.addEventListener("fullscreenerror",d=>Pa(this,d));window.addEventListener("webkitfullscreenerror",d=>Pa(this,d));window.addEventListener("mozfullscreenerror",d=>Pa(this,d));if(b.oc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;
if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):J(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(F.Hb(!0),M(this)):"exited-fullscreen"===d?(F.Hb(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Qa=new Set;this.Ub=new WeakSet;this.ta=!1}Zc(){window.addEventListener("focus",()=>{k(this,"window-focus",
null,H)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},H);this.sb=0});window.addEventListener("focusin",a=>{a=a.target;(Aa.has(a.tagName.toLowerCase())||J(a))&&k(this,"keyboard-blur",null,H)});window.addEventListener("keydown",a=>Qa(this,"keydown",a));window.addEventListener("keyup",a=>Qa(this,"keyup",a));window.addEventListener("dblclick",a=>Ra(this,"dblclick",a,G));window.addEventListener("wheel",
a=>{this.Y||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Z,pageX:a.pageX,pageY:a.pageY+this.Z,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},G)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Sa(a);N(this,"pointerdown",a)}),this.v.ia&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.vb=new self.le(()=>{N(this,"pointermove",this.Oa);this.Oa=null}),this.vb.qd=!0,window.addEventListener("pointerrawupdate",
a=>{this.Oa&&(this.Zb+=this.Oa.movementX||0,this.$b+=this.Oa.movementY||0);this.Oa=a;a=this.vb;if(-1===a.Wa){var c=Date.now(),d=c-a.Pb,e=a.Je;d>=e&&a.qd?(a.Pb=c,a.lb=!0,a.Gc(),a.lb=!1):a.Wa=self.setTimeout(a.Od,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Sa(a);Ua(this,"pointerdown",a)}),
window.addEventListener("mousemove",a=>Ua(this,"pointermove",a)),window.addEventListener("mouseup",a=>Ua(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Sa(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=()=>this.Bc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",
b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.ge()&&!this.v.dd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Va(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}sa(){return this.v.sa()}ja(){return this.v.ja()}Bc(){var b=[...this.Qa];this.Qa.clear();if(!this.ta)for(const a of b)(b=a.play())&&b.catch(()=>{this.Ub.has(a)||this.Qa.add(a)})}ya(b){if("function"!==
typeof b.play)throw Error("missing play function");this.Ub.delete(b);let a;try{a=b.play()}catch(c){this.Qa.add(b);return}a&&a.catch(()=>{this.Ub.has(b)||this.Qa.add(b)})}Ia(b){this.Qa.delete(b);this.Ub.add(b)}Eb(b){this.ta=!!b}xc(b){alert(b.message)}});"use strict";
async function pa(b){if(b.Ie)throw Error("already initialised");b.Ie=!0;var a=b.cc.uc("dispatchworker.js");b.Ic=await b.cc.jc(a,b.fb,{name:"DispatchWorker"});a=new MessageChannel;b.Nc=a.port1;b.Ic.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Tc=await sa(b)}function ra(b){return[b.Nc,b.Tc]}
async function sa(b){const a=b.Ad.length;var c=b.cc.uc("jobworker.js");c=await b.cc.jc(c,b.fb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Ic.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Ad.push(c);return e.port1}
self.je=class{constructor(b){this.cc=b;this.fb=b.aa;this.fb="preview"===b.A?this.fb+"workers/":this.fb+b.dc;this.Le=Math.min(navigator.hardwareConcurrency||2,16);this.Ic=null;this.Ad=[];this.Tc=this.Nc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.qa({Ze:!0,$e:"workermain.js",Xa:["scripts/c3runtime.js"],hc:[],Wc:"",We:"scripts/",Yc:[],Pd:"html5"}));"use strict";
async function Ya(b,a){a=a.type;let c=!0;0===a?c=await $a():1===a&&(c=await ab());k(b,"permission-result",{type:a,result:c})}async function $a(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function ab(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.qa.Ya(class extends self.Ga{constructor(b){super(b,"touch");n(this,"request-permission",a=>Ya(this,a))}});"use strict";const bb=180/Math.PI;
async function cb(b,a){a.isiOSCordova&&(b.Xb=!0);b.Vc=a.timeScaleMode;b.Gd=["equalpower","HRTF","soundfield"][a.panningModel];b.rd=["linear","inverse","exponential"][a.distanceModel];b.Hd=a.refDistance;b.Fd=a.maxDistance;b.Jd=a.rolloffFactor;if(b.v.Oc)b.Xb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.td)});else{var c={latencyHint:a.latencyHint};b.Md||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");db(b);b.g.onstatechange=()=>{"running"!==b.g.state&&db(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ma=b.g.createGain();b.Ma.connect(b.g.destination);c=a.listenerPos;b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",
d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function eb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Bd=g;fb(b,g);try{b.la=await gb(b,c,d,e,g,f);if(q){Q(b.la,!0);var y=b.la,W=q.innerAngle,C=q.outerAngle,tb=q.outerGain;if(y.mb){hb(y,q.x,q.y,q.angle);var Fa=self.Za.ne;y.F.coneInnerAngle=Fa(W);y.F.coneOuterAngle=
Fa(C);y.F.coneOuterGain=tb}q.hasOwnProperty("uid")&&(b.la.ka=q.uid)}else Q(b.la,!1);b.la.Play(h,m,p,t)}catch(ub){console.error("[Construct] Audio: error starting playback: ",ub);return}finally{c=b.ub.get(g);if(!c)throw Error("expected pending tag");c.Xc--;0===c.Xc&&(c.resolve(),b.ub.delete(g))}u(b)}
async function ib(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await jb(b,c);for(const q of R(b,c)){c=q;var f=d,g=e,h=a;if(!c.Na){var m=c.N.gain;m.cancelScheduledValues(0);var p=c.s.g.currentTime;g=p+g;m.setValueAtTime(m.value,p);m.linearRampToValueAtTime(f,g);c.Fa=f;c.jb=g;c.Ld=h}}S(b)}async function kb(b,a){const c=a.tag;a=a.rate;await jb(b,c);for(const d of R(b,c))b=d,b.ha!==a&&(b.ha=a,b.za())}
async function lb(b,a){const c=a.tag;a=a.pos;await jb(b,c);for(const d of R(b,c))d.pc(a)}async function mb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await gb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function nb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ea.indexOf(a),-1!==a&&b.ea.splice(a,1)}
async function ob(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Vd(b,...e);else if("delay"===c)e=new self.Td(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Sd(b,c.da,...e);var f=a.bufferType;c.od=a.bufferOriginalUrl;c.pd=f}else if("flanger"===c)e=new self.Wd(b,...e);else if("phaser"===c)e=new self.Yd(b,...e);else if("gain"===c)e=
new self.Xd(b,...e);else if("tremolo"===c)e=new self.$d(b,...e);else if("ringmod"===c)e=new self.Zd(b,...e);else if("distortion"===c)e=new self.Ud(b,...e);else if("compressor"===c)e=new self.Rd(b,...e);else if("analyser"===c)e=new self.Qd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.fa.get(d);e||(e=[],b.fa.set(d,e));a.yd=e.length;a.ba=d;e.push(a);pb(b,d);qb(b)}
async function rb(b,a){const c=a.saveLoadMode;if(3!==c)for(var d of b.L)d.xa()&&1===c||(d.xa()||2!==c)&&d.ra();for(const e of b.fa.values())for(const f of e)f.j();b.fa.clear();b.ec=a.timeScale;b.Kc=a.gameTime;d=a.listenerPos;b.g.listener.setPosition(d[0],d[1],d[2]);b.ta=a.isSilent;b.v.Eb(b.ta);b.Tb=a.masterVolume;b.Ma.gain.value=b.Tb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>ob(b,f))));await Promise.all(d);await Promise.all(a.playing.map(e=>sb(b,e,c)));S(b)}
async function vb(b,a){try{const c=b.g.suspend(a.time);b.xd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Cb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>wb(d)),b.xd=!0);await c}catch(c){wb(c)}}
function db(b){b.Mb||(b.Mc=!1,window.addEventListener("pointerup",b.va,!0),window.addEventListener("touchend",b.va,!0),window.addEventListener("click",b.va,!0),window.addEventListener("keydown",b.va,!0),b.Mb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ea)if(g.ab()===c)return await xb(g),g;if(f)return null;if(e&&(b.Xb||b.wd)){f=0;for(let h=0,m=b.ea.length;h<m;++h)g=b.ea[h],b.ea[f]=g,g.xa()?g.j():++f;b.ea.length=f}f="audio/webm; codecs=opus"===d&&!b.Md;e&&f&&(b.wd=!0);c=!e||b.Xb||f?new self.ce(b,a,c,d,e,f):new self.ae(b,a,c,d,e);b.ea.push(c);await xb(c);b.Ed.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ca()}),b.Ed.add(a));return c}
function yb(b,a){return(a=b.fa.get(a.toLowerCase()))?a[0].R():b.wa()}function pb(b,a){let c=b.wa();var d=b.fa.get(a);if(d&&d.length){c=d[0].R();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.wa()):e.U(d[f+1].R())}}for(const f of R(b,a))d=c,e=f.F||f.N,e.disconnect(),e.connect(d);b.Ca&&b.Rc===a&&(b.Ca.disconnect(),b.Ca.connect(c))}function*R(b,a){if(a)for(const c of b.L)b=c.ba,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.la&&!b.la.S()&&(yield b.la)}
function zb(b,a,c){return c?b.v.He(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Ab(b,a){let c=0;for(let d=0,e=b.L.length;d<e;++d){const f=b.L[d];b.L[c]=f;f.M===a?f.j():++c}b.L.length=c}async function gb(b,a,c,d,e,f){for(const g of b.L)if(g.ab()===c&&(g.ic()||f))return g.ba=e,g;a=await P(b,a,c,d,f);e="html5"===a.Ec?new self.be(a.s,a,e):new self.de(a.s,a,e);b.L.push(e);return e}
function fb(b,a){let c=b.ub.get(a);if(!c){let d=null;c={Xc:0,promise:new Promise(e=>d=e),resolve:d};b.ub.set(a,c)}c.Xc++}function jb(b,a){a||(a=b.Bd);return(b=b.ub.get(a))?b.promise:Promise.resolve()}function S(b){if(0<b.La.size)u(b);else for(const a of b.L)if(!a.G&&!a.S()){u(b);break}}function Bb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function qb(b){b.Pc||(b.Pc=!0,Promise.resolve().then(()=>Cb(b)))}
function Cb(b){const a={};for(const [c,d]of b.fa)a[c]=d.map(e=>e.$a());k(b,"fxstate",{fxstate:a});b.Pc=!1}
async function sb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await gb(b,d,e,f,h,g)}catch(t){console.error("[Construct] Audio: error loading audio state: ",t);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.oa[0]=f[0],b.oa[1]=f[1],b.oa[2]=f[2],f=d.orient,b.na[0]=f[0],b.na[1]=f[1],b.na[2]=f[2],e.setPosition(...b.oa),e.setOrientation(...b.na),e.coneInnerAngle=d.cia,e.coneOuterAngle=
d.coa,e.coneOuterGain=d.cog,b.ka=d.uid):Q(b,!1);c.Play(m,p,q,0);a.isPlaying||c.cb();c.wc(a)}}}function wb(b){console.error("[Audio] Offline rendering error: ",b)}
self.Za=class extends self.Ga{constructor(b){super(b,"audio");this.Ma=this.g=null;this.Mb=this.Mc=!1;this.va=()=>{if(!this.Mc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Mb&&(this.Mc=!0,window.removeEventListener("pointerup",this.va,!0),window.removeEventListener("touchend",this.va,!0),window.removeEventListener("click",this.va,!0),window.removeEventListener("keydown",
this.va,!0),this.Mb=!1)}};this.ea=[];this.L=[];this.la=null;this.Bd="";this.Ed=new Set;this.Cd=-1;this.ub=new Map;this.Tb=1;this.ta=!1;this.Vc=0;this.ec=1;this.Kc=0;this.Gd="HRTF";this.rd="inverse";this.Hd=600;this.Fd=1E4;this.Jd=1;this.wd=this.Xb=!1;this.Md=this.v.he();this.fa=new Map;this.La=new Set;this.xd=this.Pc=!1;this.Rc="";this.Ca=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ca&&this.Ca.disconnect();this.Rc=c.toLowerCase();this.Ca=this.g.createMediaStreamSource(a);this.Ca.connect(yb(this,
this.Rc))};this.Kb=null;self.C3Audio_GetOutputStream=()=>{this.Kb||(this.Kb=this.g.createMediaStreamDestination(),this.Ma.connect(this.Kb));return this.Kb.stream};self.C3Audio_DOMInterface=this;r(this,[["create-audio-context",a=>cb(this,a)],["play",a=>eb(this,a)],["stop",a=>{a=a.tag;for(const c of R(this,a))c.ra()}],["stop-all",()=>{for(const a of this.L)a.ra()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of R(this,c))a?d.cb():d.Db();S(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;for(const d of R(this,
c))T(d,a)}],["fade-volume",a=>ib(this,a)],["set-master-volume",a=>{this.Tb=a.vol;this.Ma.gain.value=this.Tb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of R(this,c))Db(d,a)}],["set-silent",a=>{this.ta=a.isSilent;this.v.Eb(this.ta);for(const c of this.L)c.Ib()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of R(this,c))d.qc(a)}],["set-playback-rate",a=>kb(this,a)],["seek",a=>lb(this,a)],["preload",a=>mb(this,a)],["unload",a=>nb(this,a)],["unload-all",()=>{for(const a of this.ea)a.j();
this.ea.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.L)c.rc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>ob(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.fa.get(a.tag);!a||0>c||c>=a.length||(a[c].$(d,e,f,g),qb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.fa.get(a);if(c&&c.length){for(const d of c)d.j();this.fa.delete(a);pb(this,a)}}],["tick",a=>{this.ec=a.timeScale;
this.Kc=a.gameTime;this.Cd=a.tickCount;if(0!==this.Vc)for(var c of this.L)c.za();(c=a.listenerPos)&&this.g.listener.setPosition(c[0],c[1],c[2]);for(const d of a.instPans){a=d.uid;for(const e of this.L)e.ka===a&&hb(e,d.x,d.y,d.angle)}}],["load-state",a=>rb(this,a)],["offline-render-audio",a=>vb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}X(){return this.g}wa(){return this.Ma}Bb(){return this.ta}ya(b){this.v.ya(b)}Ia(b){this.v.Ia(b)}Ja(){for(var b of this.La)b.Ja();b=this.g.currentTime;
for(var a of this.L)a.Ja(b);a=this.L.filter(c=>!c.G&&!c.S()).map(c=>c.$a());k(this,"state",{tickCount:this.Cd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.La].map(c=>({tag:c.ba,index:c.yd,peak:c.Ra,rms:c.Id,binCount:c.m.frequencyBinCount,freqBins:c.vd}))});0===a.length&&0===this.La.size&&this.Nb&&(this.v.Ge(this.Nd),this.Nb=!1)}static ne(b){return b*bb}static cd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ke(b){return Math.log(Math.max(Math.min(b,1),0))/
Math.log(10)*20}};self.qa.Ya(self.Za);"use strict";function xb(b){b.Rb||(b.Rb=b.vc());return b.Rb}self.$c=class{constructor(b,a,c,d,e){this.s=b;this.Ne=a;this.Ea=c;this.T=d;this.Ke=e;this.Ec="";this.Rb=null}j(){this.Rb=this.s=null}vc(){}X(){return this.s.X()}lc(){return this.Ne}ab(){return this.Ea}kc(){return this.T}xa(){return this.Ke}ca(){}};"use strict";
self.ae=class extends self.$c{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ec="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.ob=this.pb=null;this.K.addEventListener("canplaythrough",()=>!0);this.tb=this.X().createGain();this.rb=null;this.K.addEventListener("canplay",()=>{this.pb&&(this.pb(),this.ob=this.pb=null);!this.rb&&this.K&&(this.rb=this.X().createMediaElementSource(this.K),this.rb.connect(this.tb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ea}' error: `,f);this.ob&&(this.ob(f),this.ob=this.pb=null)})}j(){Ab(this.s,this);this.tb.disconnect();this.tb=null;this.rb.disconnect();this.rb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.j()}vc(){return new Promise((b,a)=>{this.pb=b;this.ob=a;this.K.src=this.Ea})}P(){return this.K}ca(){return this.K.duration}};"use strict";
async function Eb(b){if(b.Aa)return b.Aa;var a=b.s.v;if("cordova"===a.A&&a.ed(b.Ea)&&a.Ob)b.Aa=await a.Ab(b.Ea);else{a=await fetch(b.Ea);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Aa=await a.arrayBuffer()}}async function Fb(b){if(b.da)return b.da;b.da=await zb(b.s,b.Aa,b.Me);b.Aa=null}
self.ce=class extends self.$c{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ec="webaudio";this.da=this.Aa=null;this.Me=!!f}j(){Ab(this.s,this);this.da=this.Aa=null;super.j()}async vc(){try{await Eb(this),await Fb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ea}': `,b)}}ca(){return this.da?this.da.duration:0}};"use strict";let Gb=0;
function Q(b,a){a=!!a;b.mb!==a&&(b.mb=a,b.mb?(b.F||(b.F=b.X().createPanner(),b.F.panningModel=b.s.Gd,b.F.distanceModel=b.s.rd,b.F.refDistance=b.s.Hd,b.F.maxDistance=b.s.Fd,b.F.rolloffFactor=b.s.Jd),b.N.disconnect(),b.N.connect(b.F),b.F.connect(b.wa())):(b.F.disconnect(),b.N.disconnect(),b.N.connect(b.wa())))}function T(b,a){b.Fa=a;b.N.gain.cancelScheduledValues(0);b.jb=-1;b.N.gain.value=b.mc()}function Db(b,a){a=!!a;b.Na!==a&&(b.Na=a,b.Ib())}
function hb(b,a,c,d){b.mb&&(b.oa[0]=a,b.oa[1]=c,b.oa[2]=0,b.na[0]=Math.cos(d),b.na[1]=Math.sin(d),b.na[2]=0,b.F.setPosition(...b.oa),b.F.setOrientation(...b.na))}function U(b){return b.Qc?b.s.Kc:performance.now()/1E3}
self.ad=class{constructor(b,a,c){this.s=b;this.M=a;this.ba=c;this.Jb=Gb++;this.N=this.X().createGain();this.N.connect(this.wa());this.F=null;this.mb=!1;this.oa=[0,0,0];this.na=[0,0,0];this.G=!0;this.W=this.pa=this.I=!1;this.Fa=1;this.Na=!1;this.ha=1;b=this.s.Vc;this.Qc=1===b&&!this.xa()||2===b;this.jb=this.ka=-1;this.Ld=!1}j(){this.M=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.N.disconnect();this.N=null}X(){return this.s.X()}wa(){return yb(this.s,this.ba)}lc(){return this.M.lc()}ab(){return this.M.ab()}kc(){return this.M.kc()}xa(){return this.M.xa()}S(){}ic(){}IsPlaying(){return!this.G&&
!this.I&&!this.S()}Ha(){}ca(){return this.M.ca()}Play(){}ra(){}cb(){}Db(){}Ja(b){-1!==this.jb&&b>=this.jb&&(this.jb=-1,this.Ld&&this.ra(),Bb(this.s,"fade-ended",this.ba,this.Jb))}mc(){const b=this.Fa;return isFinite(b)?b:0}Bb(){return this.s.Bb()}Ib(){}qc(){}za(){}pc(){}rc(){}nc(){}$a(){var b=this.Jb,a=this.ba,c=this.ca(),d=this.Fa,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.oa,orient:this.na,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ka}}else f=null;return{aiid:b,
tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ha(),playbackRate:this.ha,uid:this.ka,bufferOriginalUrl:this.lc(),bufferUrl:"",bufferType:this.kc(),isMusic:this.xa(),isLooping:this.W,isMuted:this.Na,resumePosition:this.nc(),pan:f}}wc(b){var a=b.playbackRate;this.ha!==a&&(this.ha=a,this.za());Db(this,b.isMuted)}};"use strict";
self.be=class extends self.ad{constructor(b,a,c){super(b,a,c);this.M.tb.connect(this.N);this.M.onended=()=>this.yc()}j(){this.ra();this.M.tb.disconnect();super.j()}P(){return this.M.P()}yc(){this.G=!0;this.ka=-1;Bb(this.s,"ended",this.ba,this.Jb)}S(){return this.P().ended}ic(){return this.G?!0:this.S()}Ha(){let b=this.P().currentTime;this.W||(b=Math.min(b,this.ca()));return b}Play(b,a,c){const d=this.P();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.M.ab()}' to position '${c}': `,e)}this.s.ya(d);this.I=this.G=!1;this.W=b;this.ha=1}ra(){const b=this.P();b.paused||b.pause();this.s.Ia(b);this.G=!0;this.I=!1;this.ka=-1}cb(){if(!(this.I||this.G||this.S())){var b=this.P();b.paused||b.pause();this.s.Ia(b);this.I=!0}}Db(){!this.I||this.G||this.S()||(this.s.ya(this.P()),this.I=!1)}Ib(){this.P().muted=this.Na||this.Bb()}qc(b){b=!!b;this.W!==b&&(this.W=
b,this.P().loop=b)}za(){let b=this.ha;this.Qc&&(b*=this.s.ec);try{this.P().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}pc(b){if(!this.G&&!this.S())try{this.P().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}nc(){return this.Ha()}rc(b){b?this.IsPlaying()?(this.P().pause(),this.pa=!0):this.pa=!1:this.pa&&(this.s.ya(this.P()),this.pa=!1)}};"use strict";function V(b){b.o&&b.o.disconnect();b.o=null;b.eb=null}
self.de=class extends self.ad{constructor(b,a,c){super(b,a,c);this.o=null;this.Vb=d=>this.yc(d);this.Lc=!0;this.eb=null;this.O=this.Wb=this.Yb=0;this.Sc=1}j(){this.ra();V(this);this.Vb=null;super.j()}yc(b){this.I||this.pa||b.target!==this.eb||(this.G=this.Lc=!0,this.ka=-1,V(this),Bb(this.s,"ended",this.ba,this.Jb))}S(){return!this.G&&this.o&&this.o.loop||this.I?!1:this.Lc}ic(){return!this.o||this.G?!0:this.S()}Ha(){let b;b=this.I?this.O:this.Wb+(U(this)-this.Yb)*this.ha;this.W||(b=Math.min(b,this.ca()));
return b}Play(b,a,c,d){this.Sc=1;T(this,a);V(this);this.o=this.X().createBufferSource();this.o.buffer=this.M.da;this.o.connect(this.N);this.eb=this.o;this.o.onended=this.Vb;this.o.loop=b;this.o.start(d,c);this.I=this.G=this.Lc=!1;this.W=b;this.ha=1;this.Yb=U(this);this.Wb=c}ra(){if(this.o)try{this.o.stop(0)}catch(b){}this.G=!0;this.I=!1;this.ka=-1}cb(){this.I||this.G||this.S()||(this.O=this.Ha(),this.W&&(this.O%=this.ca()),this.I=!0,this.o.stop(0))}Db(){!this.I||this.G||this.S()||(V(this),this.o=
this.X().createBufferSource(),this.o.buffer=this.M.da,this.o.connect(this.N),this.eb=this.o,this.o.onended=this.Vb,this.o.loop=this.W,T(this,this.Fa),this.za(),this.o.start(0,this.O),this.Yb=U(this),this.Wb=this.O,this.I=!1)}mc(){return super.mc()*this.Sc}Ib(){this.Sc=this.Na||this.Bb()?0:1;T(this,this.Fa)}qc(b){b=!!b;this.W!==b&&(this.W=b,this.o&&(this.o.loop=b))}za(){let b=this.ha;this.Qc&&(b*=this.s.ec);this.o&&(this.o.playbackRate.value=b)}pc(b){this.G||this.S()||(this.I?this.O=b:(this.cb(),this.O=
b,this.Db()))}nc(){return this.O}rc(b){b?this.IsPlaying()?(this.pa=!0,this.O=this.Ha(),this.W&&(this.O%=this.ca()),this.o.stop(0)):this.pa=!1:this.pa&&(V(this),this.o=this.X().createBufferSource(),this.o.buffer=this.M.da,this.o.connect(this.N),this.eb=this.o,this.o.onended=this.Vb,this.o.loop=this.W,T(this,this.Fa),this.za(),this.o.start(0,this.O),this.Yb=U(this),this.Wb=this.O,this.pa=!1)}wc(b){super.wc(b);this.O=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.X();this.yd=-1;this.T=this.ba="";this.l=null}j(){this.g=null}R(){}U(){}$a(){return{type:this.T,tag:this.ba,params:this.l}}}
self.Vd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.l=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.C=this.g.createBiquadFilter();this.C.type=a;this.C.frequency.value=c;this.C.detune.value=d;this.C.Q.value=e;this.C.gain.vlaue=f;this.u.connect(this.C);this.u.connect(this.h);this.C.connect(this.i)}j(){this.u.disconnect();this.C.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.l[1]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.l[2]=a;Y(this,this.C.detune,a,c,d);break;case 3:this.l[3]=a;Y(this,this.C.Q,a,c,d);break;case 4:this.l[4]=a,Y(this,this.C.gain,a,c,d)}}};
self.Td=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.l=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.qb=X(this);this.V=this.g.createDelay(a);this.V.delayTime.value=a;this.ib=X(this);this.ib.gain.value=c;this.u.connect(this.qb);this.u.connect(this.h);this.qb.connect(this.i);this.qb.connect(this.V);this.V.connect(this.ib);this.ib.connect(this.qb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.qb.disconnect();
this.V.disconnect();this.ib.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){const e=self.Za.cd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.l[1]=e(a);Y(this,this.ib.gain,e(a),c,d);break;case 5:this.l[0]=a,Y(this,this.V.delayTime,a,c,d)}}};
self.Sd=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.l=[c,d];this.pd=this.od="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.hb=this.g.createConvolver();this.hb.normalize=c;this.hb.buffer=a;this.u.connect(this.hb);this.u.connect(this.h);this.hb.connect(this.i)}j(){this.u.disconnect();this.hb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}$a(){const b=super.$a();b.bufferOriginalUrl=this.od;b.bufferUrl="";b.bufferType=this.pd;return b}};
self.Wd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.l=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.kb=X(this);this.kb.gain.value=e;this.V=this.g.createDelay(a+c);this.V.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.J=X(this);this.J.gain.value=c;this.u.connect(this.V);this.u.connect(this.h);this.V.connect(this.i);this.V.connect(this.kb);this.kb.connect(this.V);this.B.connect(this.J);
this.J.connect(this.V.delayTime);this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.V.disconnect();this.B.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();this.kb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.l[1]=a/1E3;Y(this,this.J.gain,a/1E3,
c,d);break;case 7:this.l[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.l[3]=a/100,Y(this,this.kb.gain,a/100,c,d)}}};
self.Yd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.l=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.C=this.g.createBiquadFilter();this.C.type="allpass";this.C.frequency.value=a;this.C.detune.value=c;this.C.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.J=X(this);this.J.gain.value=e;this.u.connect(this.C);this.u.connect(this.h);this.C.connect(this.i);this.B.connect(this.J);this.J.connect(this.C.frequency);
this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.C.disconnect();this.B.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.l[0]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.l[1]=a;Y(this,this.C.detune,a,c,d);
break;case 3:this.l[2]=a;Y(this,this.C.Q,a,c,d);break;case 6:this.l[3]=a;Y(this,this.J.gain,a,c,d);break;case 7:this.l[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.Xd=class extends Z{constructor(b,a){super(b);this.T="gain";this.l=[a];this.m=X(this);this.m.gain.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(b,a,c,d){const e=self.Za.cd;switch(b){case 4:this.l[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.$d=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.l=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.J=X(this);this.J.gain.value=c/2;this.B.connect(this.J);this.J.connect(this.m.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.J.disconnect();this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.J.gain,a/2,c,d);break;case 7:this.l[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.Zd=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.l=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.wb=X(this);this.wb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.wb.gain);this.B.start(0);this.u.connect(this.wb);this.u.connect(this.h);this.wb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.wb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.l[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.Ud=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.l=[a,c,d,e,f];this.u=X(this);this.bc=X(this);this.ac=X(this);b=d;.01>b&&(b=.01);this.bc.gain.value=b;this.ac.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.fc=this.g.createWaveShaper();this.Hc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Hc[32768+e]=f,this.Hc[32768-
e-1]=-f;this.fc.curve=this.Hc;this.u.connect(this.bc);this.u.connect(this.h);this.bc.connect(this.fc);this.fc.connect(this.ac);this.ac.connect(this.i)}j(){this.u.disconnect();this.bc.disconnect();this.fc.disconnect();this.ac.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Rd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.l=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(){}};
self.Qd=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.l=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.vd=new Float32Array(this.m.frequencyBinCount);this.Kd=new Uint8Array(a);this.Id=this.Ra=0;b=this.s;b.La.add(this);S(b)}j(){this.s.La.delete(this);this.m.disconnect();super.j()}Ja(){this.m.getFloatFrequencyData(this.vd);this.m.getByteTimeDomainData(this.Kd);const b=this.m.fftSize;let a=this.Ra=0;for(var c=0;c<b;++c){let d=(this.Kd[c]-
128)/128;0>d&&(d=-d);this.Ra<d&&(this.Ra=d);a+=d*d}c=self.Za.ke;this.Ra=c(this.Ra);this.Id=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(){}};"use strict";
async function Hb(b){if(!b.Da)try{b.Da=await navigator.wakeLock.request("screen"),b.Da.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Da=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
function Ib(){var b=document.body;const a=b.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");b=getComputedStyle(b);b=[b.getPropertyValue("--temp-sai-top"),b.getPropertyValue("--temp-sai-right"),b.getPropertyValue("--temp-sai-bottom"),b.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);
return isFinite(c)?c:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return b}
self.qa.Ya(class extends self.Ga{constructor(b){super(b,"platform-info");r(this,[["get-initial-state",()=>this.zc()],["request-wake-lock",()=>Hb(this)],["release-wake-lock",()=>{this.Da&&(this.Da.release(),this.Da=null)}]]);window.addEventListener("resize",()=>{k(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Ib()})});this.Da=null}zc(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Ib(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";function Jb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Kb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.qa.Ya(class extends self.Ga{constructor(b){super(b,"browser");this.A="";r(this,[["get-initial-state",a=>this.zc(a)],["ready-for-sw-messages",()=>Jb(this)],["alert",a=>this.xc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ac(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Kb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.ef||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.A||"macos-wkwebview"===this.A)self.qa.Hb(!0),
this.v.Dc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(c):a.mozRequestFullScreen?a.mozRequestFullScreen(c):a.msRequestFullscreen?a.msRequestFullscreen(c):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",
()=>{"windows-webview2"===this.A||"macos-wkwebview"===this.A?(self.qa.Hb(!1),this.v.Dc({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}zc(b){this.A=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}xc(b){alert(b.message)}Ac(b){b=b.isFocus;if("nwjs"===this.A){const a="nwjs"===this.A?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
